### PR TITLE
Feature for checking datasets #1576

### PR DESCRIPTION
**Pull request by dassaniansh**

### CODE REVIEW

**Comment by henrykironde** [comment]
@dassaniansh, this is a good start. There are a few things to change/consider

1) looks like you added a lake dataset that was installed as Geojson in this PR. That will be removed
2) The function will take only one argument, that is the url link for example.

```
`retriever check "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/bezdekIris.data"`
This command should print out that the url exist in a dataset called iris.
```

Or 

```
`retriever check "https://archive/fake-url-does-not-exist"`
This command should print out that the url does not exist hence you can add the data.
```

**Comment by dassaniansh** [comment]
Do I need to choose a database engine if I am checking for URL to present in the database?

**Comment by henrykironde** [comment]
@dassaniansh sorry I didn't see the comment. 

> Do I need to choose a database engine if I am checking for URL to present in the database?

the user does not need to provide an engine.
At the end we are going to move this method to the file lib/create_scripts.py https://github.com/weecology/retriever/blob/main/retriever/lib/create_scripts.py

I want to see how you have used the this feature before I start to review it

**Comment by dassaniansh** [comment]
Okay sir, Can you please tell me how may I show it?

**Comment by henrykironde** [comment]
what commands have you run?

**Comment by dassaniansh** [comment]
Sorry for replying late sir, Can you please help me by pointing out or explaining that from which file does the download command work in the library, so that maybe I can replicate the same procedure with check command. Actually I had created the algorithm and added it into the get_opt.py file but whenever I am running the check command it is not able to take the argument, and I observed that the download and install command (commands which take argument) aren't called by get_opt.py file so it will be really grateful if you could explain me the working of download command.
Screenshot from 2021-05-20 17-44-10

**Comment by henrykironde** [comment]
Going to look at it today

**Comment by henrykironde** [comment]
This PR needs some more work to be able to run the commands. I will go ahead and make some adjustments so that we can test it.

**Comment by dassaniansh** [comment]
Sure @henrykironde sir, thanks for helping me out and please do let me know when can I proceed.

**Comment by dassaniansh** [comment]
@henrykironde sir, are there any updates so that I can proceed further?

**Comment by henrykironde** [comment]
@dassaniansh do you want to jump on a call right now incase you are free.

**Comment by dassaniansh** [comment]
Sure sir

**Comment by henrykironde** [comment]
Could you join gitter https://gitter.im/weecology/retriever?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by dassaniansh** [comment]
Yes sir, I have joined this gitter

**Comment by dassaniansh** [comment]
@henrykironde sir, please check the pull request as I have fixed the issue and have also tested it on my machine and it works.

**Comment by henrykironde** [comment]
Let me know if you have managed to run the code in VS with parameters. Then we shall go through this together.

**Comment by dassaniansh** [comment]
@henrykironde sir, I'm right now working with command pip install . -U which you told me and it works really fine with me, I'll look into that VS parameters after resolving this issue. We can review this pull request over a meet whenever you are free.

**Comment by henrykironde** [comment]
Include the results from some commands you have run

**Comment by dassaniansh** [comment]
It is replaced by pull request #1597

**Pull request closed without merging**
