### PR TITLE
Add updated JSON scripts to master

### PR DESCRIPTION
**Pull request by goelakash**

### CODE REVIEW

**Comment by goelakash** [comment]
@ethanwhite @henrykironde

**Comment by henrykironde** [comment]
I don't think we need this because we have the changes in the data-package branch.

**Comment by henrykironde** [comment]
let me know if am wrong

**Comment by ethanwhite** [comment]
@henrykironde - this was my idea. See https://github.com/weecology/retriever/pull/606#discussion_r75385665 for my thinking and let me know what you think.

**Comment by goelakash** [comment]
@henrykironde @ethanwhite Lets merge this so that I can do the changes in the other PR.

**Pull request merged**
