### PR TITLE
Solve minor error in setup.py

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request corrects a minor error in `setup.py` as suggested by @henrykironde.

### CODE REVIEW

**Comment by henrykironde** [comment]
Since acton-lakes is not available we could skip it using pytest -v -k "not test_fetch_order" or  commenting out the entire test function test_fetch_order. We should be passing for us to release.

**Comment by harshitbansal05** [comment]
@henrykironde I have commented out the test function.

**Comment by henrykironde** [comment]
Thanks for this.

**Comment by henrykironde** [comment]
👍

**Pull request merged**
