### PR TITLE
Add table_citations field to support multiple citations

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request tries to fix: #1303. It adds an extra field `table_citations`, to support multiple citations for a script.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Code looks good to me. Thanks @harshitbansal05!

I know I'm a bit late to the discussion on this, but I'm wondering about the need to add a new `table_citations` field instead of just using `citation`. It was mentioned that allowing lists in `citation` would break backward compatibility, but I'm not sure it would. `print("Citation:   {}".format(dataset.citation))` should produce something reasonable even if `dataset.citation` is a list. E.g.,

```python
In [2]: citation = ['first citation', 'second citation']

In [3]: print("Citation:   {}".format(citation))
Citation:   ['first citation', 'second citation']
```

Given that I'm wondering if we don't want to just use `citation` and check it's length/type to change the output format.

Apologies for bringing this up after a decision was made and I'm happy if you all decide to stick with this version. No need to convince me otherwise, just go for it. Just thought it was worth a quick mention.

**Comment by henrykironde** [comment]
Thanks @ethanwhite for the input, after testing this I think we go with the proposed design.
@harshitbansal05 could you instead convert the previous` table_citations` for `ecoregions-us` to `citation = ['first citation', 'second citation']`

**Comment by henrykironde** [comment]
I have put in the changes. Feel free to open and issue if we are wised something.

**Comment by harshitbansal05** [comment]
@henrykironde, I agree with @ethanwhite. I was thinking, that if we now support multiple citations, we should also allow the user to provide them when creating a new json script. I would like to know your views on this.

**Comment by henrykironde** [comment]
@harshitbansal05, that is something we should add. Nice catch. I will add an issue

**Comment by harshitbansal05** [comment]
@henrykironde can the user input be taken in a manner similar to keywords, i.e. `;` separated citations. I following the same method in this pr.

**Comment by henrykironde** [comment]
I was proposing that, but I think a simple list is okey. I have updated it to list

**Comment by harshitbansal05** [comment]
sorry @henrykironde, I didn't quite understand. Could you explain it, please?

**Comment by henrykironde** [comment]
@harshitbansal05, I have made the change [here](https://github.com/weecology/retriever/pull/1315/files#diff-fc5dbe2da6ff17615660b76e0fb766cdR8)

**Comment by harshitbansal05** [comment]
@henrykironde may I work on the user input part?

**Comment by henrykironde** [comment]
Go a head 👍

**Pull request closed without merging**
