### PR TITLE
[WIP] SQLite support for Spatial Data

### PR DESCRIPTION
**Pull request by ss-is-master-chief**

### CODE REVIEW

**Comment by henrykironde** [comment]
You can clean it up more, test it and add any more changes.
Let me know when you are done

**Comment by harshitbansal05** [comment]
@henrykironde I wished to work on this task. Is it still open to contributing?

**Comment by henrykironde** [comment]
@harshitbansal05 feel free to contribute 👍

**Comment by henrykironde** [comment]
Thanks @ss-is-master-chief for the initiative to get spatial data into sqlite. I will close this for this time since we have not really moved forward on it. Hope to open / reference it in the future

**Pull request closed without merging**
