### PR TITLE
[WIP]: Globi

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
I tested that URI and a work around would be to provide some custom user agents. I was about to try the custom user agent as `Data Retriever data http://www.data-retriever.org/` instead of 
`opener.addheaders=[('User-Agent','Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1941.0 Safari/537.36')]`

Hence

`opener.addheaders=[('User-Agent','Data Retriever data http://www.data-retriever.org/')]`

**Comment by zhangcandrew** [comment]
Hey Henry, does downloading from `https://s3.amazonaws.com/globi/snapshot/target/data/tsv/interactions.tsv.gz` without changing anything else work for you?

I think I tried the script with that URL and it worked for me, but this might only be a temporary address.

**Comment by henrykironde** [comment]
@zhangcandrew works fine.  By the way, the type `"archived": "gzip",` should be `"archived": "gz",. I had made a mistake

**Comment by henrykironde** [comment]
Closing, This was used for reference .

**Pull request closed without merging**
