### PR TITLE
Solve csv and download commands for tidycensus

### PR DESCRIPTION
**Pull request by kkothari2001**
Solves #1616

### CODE REVIEW

**Comment by kkothari2001** [comment]
Quoting discussion on #1616 again:
> the engine.final_cleanup() function wasn't working properly as the data_path property wasn't working properly. I solved it by setting the data_path and then calling the engine.create_raw_data_dir() function for the CSV and the Download engines.

Testing Commands and Screenshots:

CSV Test with proof of csv install
CSV test

Dowload test with proof of folder copy:
Download test

**Review by Aakash3101 — COMMENTED** [review]
LGTM!

**Comment by kkothari2001** [comment]
Do you mean the setup instructions you gave me for the installation of the R and Python libraries? I will add it in the comments on the top of the script 👍🏻

**Comment by kkothari2001** [comment]
@henrykironde Please go through the PR

**Review by Aakash3101 — APPROVED** [review]
Thanks, @kkothari2001

**Comment by henrykironde** [comment]
LGTM thank you @kkothari2001

**Comment by kkothari2001** [comment]
Thank you Henry for the review, and Aakash for the help!

**Pull request merged**
