### PR TITLE
Xml2csv test

### PR DESCRIPTION
**Pull request by coolalexzb**
In this pr, I add `xml2csv_update` function in `engine_tools.py.` This function might be useful for Gsoc 2020 project.
This function can convert `XML` file to `csv` file. Anyone can provide me more benchmark and I can add test cases? (This function also works for wrapped `XML` file)
This test data I currently use is the following:
屏幕快照 2020-04-25 下午5 34 50
屏幕快照 2020-04-25 下午5 34 55

### CODE REVIEW

**Comment by henrykironde** [comment]
@coolalexzb Make sure you do not have errors when you run these linters
```
  - flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90
  - yapf --recursive retriever/ --style=.style.yapf -d
  - pylint -rn retriever/ -f colorized --rcfile=.pylintrc
```

**Comment by coolalexzb** [comment]
Thanks for your reminder. Updated! @henrykironde

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde Should I continue with this PR as Multiple authors with @coolalexzb ?

**Comment by coolalexzb** [comment]
Sure. I am so busy recently. Sorry for the late response.

**Comment by henrykironde** [comment]
Thanks @coolalexzb we have added these changes to PR Ref: #1506

**Pull request closed without merging**
