### PR TITLE
Improve efficiency of CSV installs using SQLite strategy

### PR DESCRIPTION
**Pull request by coolalexzb**
Hi, I have improved the speed of making large installs like `breed-bird-survey` #1208 by using pandas' reading and writing functions and setting chunksize parameter . When installing and merging tables for `breed_bird_survey_counts.csv`, I do not add indexes into .csv file. I am glad that you can provide suggestion to my code. Thank you!  @henrykironde  @ethanwhite

### CODE REVIEW

**Comment by henrykironde** [comment]
Hi @coolalexzb, this is a good contribution. A failure enables us to learn a lot more about the tools we are working on, hence I am opening the PR again and I will review it in detail later. Usually tools fail in this manner a lot and its good practice that you have tried so hard  👍and you have given it some good amount of effort.

**Comment by coolalexzb** [comment]
Thanks for your help! I think another two problems are also need to be fixed. One is the problem of Nan value mentioned in #1322 . In some case Nan is seen as an empty string(''). The other may be an encoding problem. The two problems can be described clearly by the following prictures. @henrykironde

**Comment by coolalexzb** [comment]
A question I want to ask is that if I need to wait and test my code in this request until all the problems are solved and new changes are merged into master branch. Thanks! @henrykironde

**Comment by henrykironde** [comment]
@coolalexzb, usually we do need a PR to be working as good as the master branch. For example, if the master branch is passing on one platform i.e Travis, the PR should also be able to pass on that same platform. Sometimes PRs do wait for a long time before they start to pass and get merged. For GSOC, this gets to be part of your proposal's "adds on" since you are solving a problem that is part of your proposal. I believe this could take sometime to solve.

**Comment by henrykironde** [comment]
Thanks @coolalexzb for this PR. I will close it because the Sqlite engine seems to be working in the same way

**Pull request closed without merging**
