### PR TITLE
Allow installation of committed dataset with python script

### PR DESCRIPTION
**Pull request by apoorvaeternity**
This will allow installation of committed datasets which have `python` scripts.
I tried to verify several datasets(including vertnet) and it is working fine.
@henrykironde Can you give it a test at your end.

### CODE REVIEW

**Comment by apoorvaeternity** [comment]
@henrykironde Looks like `flensburg-food-web` has changed causing the build to fail.

**Comment by henrykironde** [comment]
`flensburg-food-web` did not change and it passes on other engines. It looks like there may be changes in the version of sqlite used in the tests

**Comment by apoorvaeternity** [comment]
@henrykironde I seem to have found the issue. Looks like retriever use the same engine instance throughout. So when a committed dataset is installed by setting the path using `data_path` attribute it remains set. So when another dataset uses the same engine it still tries to find the raw data in the `data_path`. So setting the `data_path` attribute back to `None` after installing the committed dataset fixes the issue.

**Comment by henrykironde** [comment]
Do you think we can come up with a test on this error.

**Pull request merged**
