### PR TITLE
Datapackage.json format

### PR DESCRIPTION
**Pull request by goelakash**

### CODE REVIEW

**Comment by goelakash** [comment]
Review needed @henrykironde

**Comment by henrykironde** [comment]
Great @goelakash , It is good that you are adhering to the  Data Package specification. I am going to discus this with Ethan and get back to you since there is a huge amount of code that will be changed due to the changes in name, shortname, ..etc.

**Comment by goelakash** [comment]
@henrykironde @ethanwhite I'll add a function to convert these JSON files to python scripts until then.

**Comment by goelakash** [comment]
@henrykironde If its okay, I rebased the branch, since there were some big changes which I think would help for future testing on this branch.

**Comment by henrykironde** [comment]
@goelakash, thanks for asking. I think it Okey if it makes your work easier.

**Pull request merged**
