### PR TITLE
Update pyretriever.rst

### PR DESCRIPTION
**Pull request by ss-is-master-chief**
added an example output to `for dataset in rt.datasets():
    print(dataset.name)`

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @ss-is-master-chief, did you build the docs locally to review the changes?

**Comment by ss-is-master-chief** [comment]
@henrykironde No Sir, I have Edited from GitHub itself and issued a PR for it. The addition was not anything major but a short addition of an example to the code for better readability for the Python users.

**Comment by henrykironde** [comment]
Every PR should be tested locally. So I recommend you test the build of docs locally. And confirm that they render well. I will then do a test and merge as appropriate.

**Comment by zhangcandrew** [comment]
Tested locally, looks good for me. Merging in, feel free to open the PR again if anything else occurs.

**Comment by ss-is-master-chief** [comment]
@zhangcandrew Thank you Sir. I am working on the Python Documentation. I'll open a PR as soon as I have the draft.

**Comment by ss-is-master-chief** [comment]
@henrykironde I mis-interpreted what you said Sir. Yes, I had executed the codes locally to generate the results.

**Pull request merged**
