### PR TITLE
Code coverage tests

### PR DESCRIPTION
**Pull request by Nageshbansal**
Increased code coverage (~5%) by adding tests for creating scripts for raster and vector datasets.

### CODE REVIEW

**Comment by Nageshbansal** [comment]
@henrykironde, appveyor is not able to install cartopy, gdal and fiona, for gdal we can install it from whl but I don't get how to download that gdal wheel in appveyor.

**Comment by henrykironde** [comment]
@Nageshbansal thanks for these changes. Could you commit amend this PR to have one or two commits. Let  me know if you need help with that.

**Comment by Nageshbansal** [comment]
Yeah sure i will amed commits and also should i create notes for installation fail of gdal and fiona in appveyor

**Comment by Nageshbansal** [comment]
I have to do like this right?
```
git reset --soft "HEAD~n"
git commit --amend
```
Assuming ~n is number of commits to softly un-commit (i.e. ~1, ~2,...)

**Comment by Nageshbansal** [comment]
Yeah sure and also should I exclude these tests for the appveyor?

**Comment by henrykironde** [comment]
Do not exclude appveyor  tests, we are trying to figure that out. Was talking to one other contributor @dassaniansh to see if he has an idea.

**Comment by Nageshbansal** [comment]
@henrykironde, the branch is updated now, can you please review this once.

**Comment by Nageshbansal** [comment]
@henrykironde any updates on this?

**Comment by Nageshbansal** [comment]
@henrykironde, please review this PR now.

**Comment by henrykironde** [comment]
Thank you

**Pull request closed without merging**
