### PR TITLE
testing dell script

### PR DESCRIPTION
**Pull request by henrykironde**
We added changes to @carol-rowe666  commit 54b59c0ead6db8b3b2571d0c52fa9b1b4e90cb08

The main idea was to replace null values ``replace('\x00', ''))``

### CODE REVIEW

**Comment by henrykironde** [comment]
I am guessing this may pass.

**Comment by ethanwhite** [comment]
This is erroring for me locally:

```
ethan@croryx:~/RetrieverCode (master)$ git checkout upstream/pr/481
Note: checking out 'upstream/pr/481'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 781aa97... testing dell script

ethan@croryx:~/RetrieverCode ((781aa97...))$ pip install . --upgrade
Processing /home/ethan/Dropbox/Informatics/Retriever/src
Requirement already up-to-date: xlrd in /home/ethan/anaconda/lib/python2.7/site-packages (from retriever===1.9.0-de)
Installing collected packages: retriever
  Found existing installation: retriever 1.9.0-de
    Uninstalling retriever-1.9.0-de:
      Successfully uninstalled retriever-1.9.0-de
  Running setup.py install for retriever ... done
Successfully installed retriever-1.9.0-de
You are using pip version 8.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

ethan@croryx:~/RetrieverCode ((781aa97...))$ retriever reset all
This will remove existing scripts, cached data, and information on database connections. Specifically it will remove the scripts and raw_data folders and the connections.config file in /home/ethan/.retriever/. Do you want to proceed? (y/N)
y

ethan@croryx:~/RetrieverCode ((781aa97...))$ retriever install csv MoM2003
Traceback (most recent call last):
  File "/home/ethan/anaconda/bin/retriever", line 9, in <module>
    load_entry_point('retriever===1.9.0-de', 'console_scripts', 'retriever')()
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/__main__.py", line 117, in main
    scripts = name_matches(script_list, args.dataset)
  File "/home/ethan/anaconda/lib/python2.7/site-packages/retriever/lib/tools.py", line 29, in name_matches
    max_ratio = max([difflib.SequenceMatcher(None, arg.lower(), factor).ratio() for factor in (script.shortname.lower(), script.name.lower(), script.filename.lower())] +
AttributeError: 'tuple' object has no attribute 'lower'
```

If I remove the `EA_Dell.py` script everything runs smoothly.

**Comment by ethanwhite** [comment]
Found it! Line 10 has a trailing comma, which makes the value for `name` a tuple instead of a string. This ends up causing an error in some code in `tools.py` that tries to do fuzzy matching of dataset names by checking against the lower case value of `name`. Since `name` is a tuple it errors when trying to convert it to lower case.

We should probably wrap the code in `tools.name_matches()` in a try catch to avoid similar bugs in scripts triggering errors in the future.

**Comment by henrykironde** [comment]
This dataset does not want to get added :)

**Comment by ethanwhite** [comment]
> This dataset does not want to get added :)

No doubt :smile: and it isn't quite over yet...

The comma change fixes the retriever and the dataset successfully installs to csv, but one the first column name has some null/special characters in front of it that mean that it doesn't work quite right in at least SQLite (e.g., you can't run SELECT * FROM on the table).

```
ethan@stice:~$ head -1 .retriever/raw_data/DELL/*
==> .retriever/raw_data/DELL/newTempTrait <==
��DataSeriesID	Trait	TraitDef	TraitOrg	AmbientTemp	TraitValueSI	TraitUnitSI	ErrorPosSI	ErrorNegSI	ErrorUnitSI	Replicates	Habitat	Labfield	ArenaValueSI	ArenaUnitSI	ObsTimeValueSI	ObsTimeUnitSI	ObsTimeNotes	ResRepValueSI	ResRepUnitSI	Location	Latitude	Longitude	TaxaPresent	ConType	Con	ConCommon	ConStage	ConIDLevel	ConKingdom	ConPhylum	ConClass	ConOrder	ConFamily	ConTrophic	ConThermy	ConTemp	ConTempMethod	ConMassValueSI	ConMassUnitSI	ConDenValueSI	ConDenTypeSI	ConDenUnitSI	ResType	Res	ResCommon	ResStage	ResIDLevel	ResKingdom	ResPhylum	ResClass	ResOrder	ResFamily	ResTrophic	ResThermy	ResTemp	ResTempMethod	ResMassValueSI	ResMassUnitSI	ResDenValueSI	ResDenTypeSI	ResDenUnitSI	CitationID	Citation	FigureTable

==> .retriever/raw_data/DELL/TempTrait_001.txt <==
��DataSeriesID	Trait	TraitDef	TraitOrg	AmbientTemp	TraitValueSI	TraitUnitSI	ErrorPosSI	ErrorNegSI	ErrorUnitSI	Replicates	Habitat	Labfield	ArenaValueSI	ArenaUnitSI	ObsTimeValueSI	ObsTimeUnitSI	ObsTimeNotes	ResRepValueSI	ResRepUnitSI	Location	Latitude	Longitude	TaxaPresent	ConType	Con	ConCommon	ConStage	ConIDLevel	ConKingdom	ConPhylum	ConClass	ConOrder	ConFamily	ConTrophic	ConThermy	ConTemp	ConTempMethod	ConMassValueSI	ConMassUnitSI	ConDenValueSI	ConDenTypeSI	ConDenUnitSI	ResType	Res	ResCommon	ResStage	ResIDLevel	ResKingdom	ResPhylum	ResClass	ResOrder	ResFamily	ResTrophic	ResThermy	ResTemp	ResTempMethod	ResMassValueSI	ResMassUnitSI	ResDenValueSI	ResDenTypeSI	ResDenUnitSI	CitationID	Citation	FigureTable
```

**Comment by henrykironde** [comment]
instead of replacing ('\x00', '')) since there are other characters to handle that i did not notice, I normalized the data.

**Comment by ethanwhite** [comment]
Erroring for me:

```
ethan@stice:~/RetrieverCode ((cda621c...))$ retriever install sqlite DELL
=> Installing Thermal dependence of biological traits 2013
Downloading TempTrait_001.txt...
must be unicode, not builtin_function_or_method
```

Same error installing to `csv`.

**Comment by henrykironde** [comment]
we should close this dataset for now. I managed to create a clean file which works well with MySQL, but fails on PostgreSQL. Some of the values have very many decimal points, more than what our system can manage. 
a working script that has been tested with clean data is in the commit message.

note changing the encoding;

``` python 
        with open(self.engine.find_file("original_TempTrait_001.txt"), 'rb') as old_data:
            with open(data_path, 'w+b') as new_data:
                data = old_data.read()
                new_data.write(data.decode('utf-16').encode('utf-8'))
```

**Comment by ethanwhite** [comment]
Sounds good. So we're closing and hoping that we can get the authors to update the data file with a clean version.

**Pull request closed without merging**
