### PR TITLE
Added keyword param in datasets

### PR DESCRIPTION
**Pull request by ShivamNegi**

### CODE REVIEW

**Comment by ShivamNegi** [comment]
This the described solution for the issue #969

**Comment by henrykironde** [comment]
why is this command not working` retriever ls  -l birds`

**Comment by ShivamNegi** [comment]
The `datasets` function has been updated to return an instance of `Script`. So in the interface it increases the functionality offered by `dataset` function.
```python
import retriever as rt
datasets = rt.datasets()
for dataset in datasets:
    print(dataset.name, dataset.keywords, dataset.title)
```
So now the `dataset` object that is created above offers all `Script` variables:
```python
dataset.addendum                   dataset.exists                     dataset.next                       dataset.retriever_minimum_version
dataset.checkengine                dataset.filename                   dataset.printMessage               dataset.tables
dataset.citation                   dataset.keywords                   dataset.public                     dataset.title
dataset.description                dataset.matches_terms              dataset.ref                        dataset.urls
dataset.download                   dataset.message                    dataset.reference_url              dataset.version
dataset.encoding                   dataset.name                       dataset.retriever                  

```
Now, I think some of these are not required that can be handled in another PR.
The `retriever ls -l birds` which was not working for CLI has been addressed. Please review.

**Comment by henrykironde** [comment]
I think I like the idea, Will review it

**Comment by henrykironde** [comment]
Tests:

Case 1: `retriever ls  -l  birds `

```
(venv35) ~\Documents\GitHub\retriever [test970 +1 ~0 -0 !]> retriever ls  -l birds
Available datasets : 8

1. Antarctic Site Inventory breeding bird survey data, 1994-2013
antarctic-breed-bird
['birds']
2. A database on visible diurnal spring migration of birds
bird-migration-data
['Taxon > Plants']
3. Bird Body Size and Life History (Lislevand et al. 2007)
bird-size
['birds', 'literature-compilation']
4. USGS North American Breeding Bird Survey
breed-bird-survey
['birds', 'continental-scale']
5. USGS North American Breeding Bird Survey 50 stop
breed-bird-survey-50stop
['birds', 'continental-scale']
6. Foraging attributes for birds and mammals (Wilman, et al., 2014)
elton-traits
['mammals', 'birds', 'literature-compilation']
7. Database of Vertebrate Home Range Sizes - Tamburello et al., 2015
home-ranges
['literature-compilation', 'birds', 'mammals', 'reptiles', 'fishes']
8. Vertnet Birds
vertnet-birds
['birds']
(venv35) ~\Documents\GitHub\retriever [test970 +1 ~0 -0 !]>

```
I think if we put a space the results would look clear

Available datasets : 8

```
1. Antarctic Site Inventory breeding bird survey data, 1994-2013
antarctic-breed-bird
['birds']

2. A database on visible diurnal spring migration of birds
bird-migration-data
['Taxon > Plants']

3. Bird Body Size and Life History (Lislevand et al. 2007)
bird-size
['birds', 'literature-compilation']
```

Case 2: 
`retriever ls -l `

This gives me errors. 

I think in get_opts
```
ls_parser.add_argument('-l', help='verbose list of datasets containing following keywords '
                                  '(lists all when no keywords are specified)',
                       nargs='*').completer = ChoicesCompleter(list(keywords_list))
```
nargs='*' should be changed. to either + or `?` . You can find out the right one.

**Comment by ShivamNegi** [comment]
I think I will go with one argument only. As the interface function `dataset` takes in `arg_keyword` as  string. This would be more understandable than passing a list in my opinion. So compromising CLI functionality of checking a list of keywords for only one keyword at time.
I have updated the line spacing.

**Comment by ShivamNegi** [comment]
Not sure why the tests are failing. Looking into it.

**Comment by ethanwhite** [comment]
This passes for me locally, so once @henrykironde is happy with the code I think it's OK to go in.

**Pull request merged**
