### PR TITLE
Adds script for Database of Vertebrate Home Range Sizes.

### PR DESCRIPTION
**Pull request by embaldridge**
Creates script for importing Database of Vertebrate Home Range Sizes by Tamburello et al. 2015 from Dryad.  Solves #332 .

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks for the contribution @embaldridge!

This wouldn't run on my machine, which is weird since it seems to be passing on Travis, but the issue was easy to fix. It looks like the you to change `NA` to `'NA'` when declaring the nulls.

**Comment by embaldridge** [comment]
@ethanwhite Oops, should work now, assuming the build still passes.

**Comment by embaldridge** [comment]
Oops, should work now.

**Comment by embaldridge** [comment]
Should be good to go now, sorry about that.

**Comment by ethanwhite** [comment]
Looks great! Thanks.

**Pull request merged**
