### PR TITLE
Update print format

### PR DESCRIPTION
**Pull request by coolalexzb**

### CODE REVIEW

**Comment by apoorvaeternity** [comment]
Hey @coolalexzb - There have been some updates to master branch. Can you rebase your branch with master and remove the conflicts so that we can merge.

**Comment by coolalexzb** [comment]
Hi @apoorvaeternity, sorry for the late response because I am so busy in the last month of this semester. I have updated the commit and all the tests have passed but there exist some problems with the test environment.  But you can merge this pr.

**Comment by coolalexzb** [comment]
Normalize code to pass test

**Comment by henrykironde** [comment]
Thanks you @coolalexzb for the work on this PR. We realized that some of the tools using the Data retriever still test on older versions that may fail due to some of these changes. We hope to add them later in the future. Am closing this for now

**Pull request closed without merging**
