### PR TITLE
Gracefully handle failed downloads

### PR DESCRIPTION
**Pull request by coolalexzb**
In most case, we meet failed download problem #903 due to network interrupts and we always terminate the command by KeyboardInterrupt. To solve the problem cause by this reason, I rename partial downloaded data as 'filename.part' file. When the data is downloaded completely, 'filename.part' file will be moved to 'filename' file. I test airports dataset and it works well. However, some datasets do not contain 'content-length' element in headers, I do not find way to resume downloading this type of data. I am glad that you can provide suggestion to my code. Thank you! @henrykironde @ethanwhite

### CODE REVIEW

**Comment by henrykironde** [comment]
The branch is not updated. Could you rebase with master and squash the commits.

**Comment by coolalexzb** [comment]
> The branch is not updated. Could you rebase with master and squash the commits.
I rebased with master and squashed the commits

**Comment by coolalexzb** [comment]
Opeartion has been done. @henrykironde

**Comment by henrykironde** [comment]
@coolalexzb, I do not think you managed to update/squash the commit. Let me know in case you want some help with that.

**Comment by coolalexzb** [comment]
I squashed commits which tagged by 'download problem by KeyboardInterrupt'. Do you mean I also need to merge previous commits related to add prairie-forest datasets into one as well? @henrykironde

**Pull request closed without merging**
