### PR TITLE
Update Scripts to json

### PR DESCRIPTION
**Pull request by goelakash**
@ethanwhite

### CODE REVIEW

**Comment by goelakash** [comment]
Appveyor is failing due to `pyyaml` install error on Windows in Python 3, which might be ignored.

**Comment by ethanwhite** [comment]
Ah, I see you're merging this into `weecology:scripts-to-json`, which is why there are 111 commits. Unfortunately this makes this really difficult to review since I'm seeing 111 commits worth of changes. We either need to rebase the `weecology` branch off of master so that it's clear what's going on in this PR or think about PRing this into master.

Can you remind me of the current state of things? Are there changes in `weecology:scripts-to-json` that aren't in `master`?

**Comment by goelakash** [comment]
Basically, the scripts-to-json branch needs the new bug fixes and tests so
that we can continue to develop on that. I have some changes in my JSON
branch that I rebased on master, with the changes relevant to current tests.

**Comment by ethanwhite** [comment]
Ah, I think I misunderstood. So you just want this merged so you can get back to work in the branch, you're not looking for review?

**Comment by goelakash** [comment]
No :smile:

**Pull request merged**
