### PR TITLE
Fixed Issue #165

### PR DESCRIPTION
**Pull request by rajat503**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks for looking into this @rajat503, and sorry for being so slow getting back to you. This doesn't seem to be working for me at the moment. The key test is to install multi-table datasets using the GUI. So run `retriever` on it's own, select the JSON engine, and then install either `Vascular plan composition - McGlinn, et al., 2010` or `Vegetation plots - del Moral, 2010`.

When I do this with your branch I see two things:
1. An error: `Error: 'utf8' codec can't decode byte 0xF6 in position 51: invalid start byte
2. Not all of the files have the correct ending.

Does this specific test work for you?

**Comment by rajat503** [comment]
Hi @ethanwhite : The bug fix I provided works for duplicate ']' endings while downloading multiple datasets. Refer #165. I'll have to look into what is going wrong with multi-table datasets - it does seem to have incorrect file endings.

**Comment by ethanwhite** [comment]
Ah yes, sorry about that @rajat503, you're totally right. It looks like the json engine has other issues that need to be fixed, but they are separate from this. If you can submit this without the changes to `engines/__init__.py` and the csv engine rename I can get this in. Please also provide a more descriptive commit message, something like "Make sure that extra hard brackets aren't added to end of json files".

The reason I'm asking you to remove the changes to `engines/__init__.py` and the csv engine rename  from this PR is that since the json engine isn't fully working yet, we don't want it enabled, and because the csv engine rename should happen in it's own PR.

**Comment by rajat503** [comment]
Hi @ethanwhite, Made the changes that you suggested!

**Comment by ethanwhite** [comment]
Thanks! The changes look good, but the history is a little messy. I can merge this myself manually and clean up the history or we can walk through how to do it yourself. If you'd like to try it yourself you'll want to:

Run `git rebase -i HEAD~4 master`

You'll see a screen that looks like:

```
pick 2d06498 fixed issue #165
pick faa8a3f fixed issue #165
pick 93a0ccd Extra hard brackets no longer added at end of json file
pick d44f29c Extra hard brackets no longer added at end of json file
```

Edit it to

```
reword 2d06498 fixed issue #165
squash faa8a3f fixed issue #165
squash 93a0ccd Extra hard brackets no longer added at end of json file
squash d44f29c Extra hard brackets no longer added at end of json file
```

This will combine all of the commits into one commit and give you the chance to reword the commit message. Save this file.

You'll then be given a chance to reword the `fixed issue #165` commit. Replace it with your `Extra hard brackets no longer added at end of json file` message.

This will then pop up a combined commit message that shows the commits from all of the different commit messages. Edit this to just have the single good commit message.

Since you've rewritten the history you'll now need to force the push to GitHub. This is to stop you from accidentally changing the history of work that others have been building on, but since this is a PR with no one else working on it, it's OK to change the history:

`git push -F origin master`

If you'd rather I handle this, or you run into trouble along the way, just let me know.

**Comment by rajat503** [comment]
Thanks @ethanwhite, Cleaned it up!

**Comment by ethanwhite** [comment]
Perfect! Thanks @rajat503.

**Pull request merged**
