### PR TITLE
Add airports dataset

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Addresses #966

### CODE REVIEW

**Comment by zhangcandrew** [comment]
Thanks @apoorvaeternity!

It's looking good. One thing though, could you include the fields in each of the tables under resources? Doing so makes retriever installation go by faster.

**Comment by apoorvaeternity** [comment]
@zhangcandrew Okay I will do it by today.

**Comment by apoorvaeternity** [comment]
@zhangcandrew How does it look now?

**Comment by zhangcandrew** [comment]
Looks good! I will have to download it and test it when I can, but for now it seems like they've taken down data from the [site](http://ourairports.com/data/). For some reason, they changed 3 csvs (airport_frequencies, runways, and navaids) to be all blank today (1/16/2018).

**Comment by apoorvaeternity** [comment]
And the other three csvs (airports, countries and regions) just have the column names and no data.

**Comment by henrykironde** [comment]
@apoorvaeternity, thank you for the contribution and the patience.

**Comment by ethanwhite** [comment]
Looks like the data is all back up now. Probably just caught them in the middle of an update.

**Comment by henrykironde** [comment]
Oh yah I have checked it.

**Comment by ethanwhite** [comment]
> Oh yah I have checked it.

Of course you were way ahead of me :smile:. Nice work all!

**Pull request merged**
