### PR TITLE
Create gdp.json

### PR DESCRIPTION
**Pull request by shreyneil**
The Following pr is with reference with the following issue https://github.com/weecology/retriever/issues/967 . 
There was some problem with the data package as the latest json schema did not support the format provided 
in the datapackage , as a result i have to include all the years from 1960 to 2017 as columns to my table. 
Please verify and get back.

### CODE REVIEW

**Comment by henrykironde** [comment]
@shreyneil a good start. Let's remove the gdp.py file.
In the Json file the fields are 
Country Name, Country Code, Year Value 

```
{
  "citation": "NA",
  "description": "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV.",
  "encoding": "UTF-8",
  "homepage": "https://github.com/datasets/gdp/blob/master",
  "keywords": [
    "GDP",
    "World",
    "Gross Domestic Product",
    "Time Series"
  ],
  "name": "gdp",
  "resources": [
    {
      "dialect": {
        "do_not_bulk_insert": "False"
      },
      "name": "gdp",
      "schema": {
        "fields": [
          {
            "name": "Country Name",
            "type": "char"
          },
          {
            "name": "Country Code",
            "type": "char"
          },
          {
            "name": "Year value",
            "type": "double"
          }
        ]
      },
      "url": "http://api.worldbank.org/indicator/NY.GDP.MKTP.CD?format=csv"
    }
  ],
  "retriever": "True",
  "retriever_minimum_version": "2.0.dev",
  "title": "GDP Data",
  "urls": {
    "gdp": "http://api.worldbank.org/indicator/NY.GDP.MKTP.CD?format=csv"
  },
  "version": "1.0.0"
}
```

**Comment by henrykironde** [comment]
Use http://jsoneditoronline.org/ to format json files

**Comment by shreyneil** [comment]
Done.

**Comment by henrykironde** [comment]
@shreyneil, I have used  retriever to install this dataset and the files are not the same as the source.
https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv
 
We have the fields wrong
```
        "fields": [
          {
            "name": "Country Name",
            "type": "char"
          },
          {
            "name": "Country Code",
            "type": "char"
          },
          {
            "name": "Year",
            "type": "double"
          },
          {
            "name": "Value",
            "type": "double"
          }
```

And the URL to the data is `https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv`

Make sure only one line diff is present in the version.txt
https://github.com/weecology/retriever/pull/1040/files#diff-5fb01c6f8b54d96c62af3415c51ffad3R84

Run this dataset on retriever and post the results . Example of iris dataset run
~\Documents\GitHub\retriever [test1040 +1 ~1 -0 !]> retriever install sqlite iris
=> Installing iris

```
Downloading bezdekIris.data...
Creating table iris_Iris...
Progress: 151/151 rows inserted into iris_Iris totaling 151:
```

**Comment by shreyneil** [comment]
Done , sir i changed the field values and the version.txt file to include my json file.
Some results i got for the csv engine are:

=> Installing gdp

Downloading gdp.csv...
100%  0 seconds Progress: 1000/11507 rows inserted into ./gdp_gdp.csv totaling 1Progress: 11507/11507 rows inserted into ./gdp_gdp.csv totaling 11507:

Done!

**Comment by henrykironde** [comment]
@shreyneil, I think this is ready. Could you rebase this to master and squash the commits.
Make sure the version.txt file shows one line changed and that should have the new script name and version.

**Comment by henrykironde** [comment]
@shreyneil, Thank you  👍, its merged

**Pull request merged**
