### PR TITLE
[WIP]: Create Formatted_build.sh

### PR DESCRIPTION
**Pull request by shreyneil**
The Following PR Fixes https://github.com/weecology/retriever/issues/1012 .
Please verify and get back.

### CODE REVIEW

**Comment by shreyneil** [comment]
@henrykironde  any updates on this PR?

**Comment by henrykironde** [comment]
To make this work, we first have tests running on mac OSX. 

https://docs.travis-ci.com/user/multi-os/
https://circleci.com/build-environments/xcode/osx/

**Comment by henrykironde** [comment]
@shreyneil. This does not solve #1012 but it is a good start. On what system did you run this?

**Comment by henrykironde** [comment]
I will update you on the way forward with this PR, for now let us add a `WIP`

**Comment by ethanwhite** [comment]
Closing because we are dropping support for all installation platforms other than PyPI, conda, and source. Thanks for all of your work on this @shreyneil!

**Pull request closed without merging**
