### PR TITLE
Updated Dockerfile

### PR DESCRIPTION
**Pull request by dassaniansh**

### CODE REVIEW

**Comment by Aakash3101** [comment]
@dassaniansh This dockerfile is abandoned and not used in any workflow.

**Comment by dassaniansh** [comment]
> @dassaniansh This dockerfile is abandoned and not used in any workflow.

Yeah I merged both dockerfile's into one, Is it fine now?

**Comment by Aakash3101** [comment]
You don't need to make any changes in this Dockerfile, if look at the repository we use the Dockerfile which is present at the root of the project. In the new workflow, I am not using any Dockerfile and docker-compose.yml. So making any changes in them is not going to change the workflow.

**Comment by henrykironde** [comment]
Thanks for the changes @dassaniansh.
The changes in docker/Dockerfile  will enable us automatically register the docker file to the docker registry.
This will make it possible for users to pull the docker image of retriever from docker hub using `docker pull weecology/retriever`

**Pull request merged**
