### PR TITLE
Update scripts to match datapackage spec

### LINKED ISSUE #518: Change the tags/keywords syntax
Currently, keywords are stored as `key > value` strings in the `.script` and `.py` scripts.
I was thinking that we could change it to dicts (`{key:value}`) syntax.

For example, from `AmnioteLH.py`:

`tags=['Taxon > Mammals', 'Data Type > Compilation']`

could be made:

`tags={'Taxon' : 'Mammals', 'Data Type' : 'Compilation']`

@ethanwhite @henrykironde @Deborah-Digges

### PR DESCRIPTION
**Pull request by ethanwhite**
Updates dataset files to match datapackage specification.

1. Makes names lowercase and more descriptive
2. Using `missingValues` instead of `nulls` in json files
3. Move to three level semantic versioning for script numbers
4. Use `keywords` instead of `tags` and switch to non-categorized keywords
5. General cleanup of names, descriptions, and titles

Fixes #518, #754, #755, #756.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Ready for review. Given the number of dataset scripts touched (basically all of them) we should definitely run `try_install_all` again on at least one system.

**Comment by ethanwhite** [comment]
Current errors on this PR (Ubuntu + Python 3):

```
Engine, Dataset, Error
('mysql', 'home-ranges', ProgrammingError(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Tucker, M. A., T. J. Ord, and T. L. Rogers. 2014. Evolutionary predictors of mam' at line 1"))
('xml', 'plant-occur-oosting', IndexError('list index out of range',))
('csv', 'forest-inventory-analysis', IndexError('list index out of range',))
('json', 'forest-inventory-analysis', IndexError('list index out of range',))
('mysql', 'forest-inventory-analysis', IndexError('list index out of range',))
('xml', 'forest-inventory-analysis', IndexError('list index out of range',))
('postgres', 'forest-inventory-analysis', IndexError('list index out of range',))
('sqlite', 'forest-inventory-analysis', IndexError('list index out of range',))
```

I suspect these are all also in master at the moment in which case this PR looks good from a testing perspective.

**Comment by ethanwhite** [comment]
I've confirmed that all of these errors are also present in the current `master`.

**Comment by ethanwhite** [comment]
This is not ready to go in yet. I forgot to run version.py and doing so has revealed some other issues. Working on it now.

**Comment by ethanwhite** [comment]
OK, turned out it was just some issues with my work system. `version.txt` has now been updated so this should be in good shape as far as I can tell.

**Comment by henrykironde** [comment]
Engine, Dataset, Error
('sqlite', 'forest-plots-wghats', OperationalError('no such table: forest_plots_wghats_macroplots',))
('postgres', 'forest-plots-wghats', ProgrammingError('relation "testschema.macroplots" does not exist\nLINE 1: INSERT INTO testschema.macroplots (plotid, spcode, tree, Tre...\n                    ^\n',))
('mysql', 'forest-plots-wghats', ProgrammingError(1146, "Table 'testdb.macroplots' doesn't exist"))
('mysql', 'plant-life-hist-eu', ProgrammingError(1146, "Table 'testdb.seed_number' doesn't exist"))
('xml', 'plant-occur-oosting', IndexError('list index out of range',))

**Comment by henrykironde** [comment]
Thanks @ethanwhite

**Pull request merged**
