### PR TITLE
Add default param in reset_retriever

### PR DESCRIPTION
**Pull request by ShivamNegi**

### CODE REVIEW

**Comment by henrykironde** [comment]
@ShivamNegi, How about we refactor warning_messages

```
    warning_messages = {
        'all': "\nThis will remove existing scripts, cached data\n"
               "Specifically the scripts and raw_data folders in {}."
               "\nDo you want to proceed? (y/N)\n",
        'scripts': "\nThis will remove existing scripts."
                   "\nSpecifically it will remove the scripts folder in {}."
                   "\nDo you want to proceed? (y/N)\n",
        'data': "\nThis will remove raw data cached by the Retriever."
                "\nSpecifically it will remove the raw_data folder in {}."
                "\nDo you want to proceed? (y/N)\n",
    }


```

**Comment by ShivamNegi** [comment]
Refactor how? Do you have anything in mind?

**Comment by henrykironde** [comment]
just replace it with the one I have commented here

**Comment by henrykironde** [comment]
I will put in a PR for this late because I want to rebase

**Pull request merged**
