### PR TITLE
Added RDatasets API

### PR DESCRIPTION
**Pull request by Aakash3101**
## Currently the number of datasets present in RDatasets is 1737
---
### This [URL](https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv) displays the names of the datasets present on the Rdatasets repository.
---
1. `retriever ls rdataset`  to display all available rdatasets

2. `retriever ls rdataset all` to display all the packages present in rdatasets

3. `retriever ls rdataset -p <package>` to display all the rdatasets
    present in the R package(s) provided

4. `retriever download  rdataset-<package>-<dataset>`
    to download raw data files for the given rdataset

5. `retriever install <engine> rdataset-<package>-<dataset>`
    to install the rdataset by creating its script and installing
    it to the given engine

---
I will try to see if I can write some tests for it. And I will also start writing the documentation for it, as I did for Socrata API.

### CODE REVIEW

**Comment by Aakash3101** [comment]
## CLI Examples
---
- `retriever ls rdataset`: Lists all the RDatasets present with their package name and dataset name

### Output
```
List of all available Rdatasets

Package: aer	 Dataset: affairs
Package: aer	 Dataset: argentinacpi
Package: aer	 Dataset: bankwages
...
```
- `retriever ls rdataset -p vcd`: Lists all the RDatasets present in the package `vcd`
### Output
```
List of all available Rdatasets in packages: ['vcd']
Package: vcd	Dataset: arthritis
Package: vcd	Dataset: baseball
Package: vcd	Dataset: brokenmarriage
...
```
- `retriever ls rdataset -p vcd aer`: Lists all the RDatasets present in the packages `vcd` and `aer`
### Output
```
List of all available Rdatasets in packages: ['vcd', 'aer']
Package: vcd	Dataset: arthritis
Package: vcd	Dataset: baseball
Package: vcd	Dataset: brokenmarriage
...
Package: aer	 Dataset: affairs
Package: aer	 Dataset: argentinacpi
Package: aer	 Dataset: bankwages
...
```
- `retriever download rdataset-vcd-bundesliga`: Downloads the `bundesliga` dataset present in the package `vcd`.
### Output
```
=> Installing rdataset-vcd-bundesliga
Downloading Bundesliga.csv: 60.0B [00:00, 117B/s]                                                                                                 
Done!
```
- `retriever install postgres rdataset-aer-usmoney`
```
=> Installing rdataset-aer-usmoney
Downloading USMoney.csv: 1.00B [00:00, 2.52B/s]
Processing... USMoney.csv
Successfully wrote scripts to /home/aakash01/.retriever/rdataset-scripts/usmoney.csv.json
Updating script name to rdataset-aer-usmoney.json
Updating the contents of script rdataset-aer-usmoney
Successfully updated rdataset_aer_usmoney.json
Updated the script rdataset-aer-usmoney
Creating database rdataset_aer_usmoney...

Installing rdataset_aer_usmoney.usmoney
Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 136/136 [00:00<00:00, 2225.09rows/s]
Done!
```

**Comment by ethanwhite** [comment]
@Aakash3101 - this looks amazing! Great work!

I have a two thoughts about the UI, the first of which is probably pretty easy, but the second of which may be harder:

1. After I get a list of the datasets from `ls` I feel like I want a dataset code that I can copy for the install. Right now I have to construct that identifier manually by typing in three things separated by `-`. What do you think about adding a column to the `retriever ls rdataset` output that has the code you need (e.g., `rdataset-tidyr-who`).
2. It would be nice if autocomplete worked for rdataset data. So I could start typing `retriever install csv rdataset-tidyr-` and then hit tab to see the available completions. I'm wondering if this is possible by appending the list of rdataset scripts to `script_list` in `get_opts.py`. A quick glance at the code suggests that `ls` is creating it's list of scripts separately, which helps, but this might still take a bit of work and I'm certainly OK with not doing it.

@henrykironde - what do you think?

**Comment by Aakash3101** [comment]
@ethanwhite I think I could implement the first part. For the second part, we actually create scripts only if the engine specified is not `download`. So we create scripts when the dataset is installed for the first time, after that the scripts function like any other script.

So the autocomplete functionality does work only when the rdataset script exists. The autocompleted suggestions would be according to the rdataset scripts that are present locally.

From what you have mentioned it does feel feasible and I think I can add a function which would create these script names and store them somewhere, and then we can pass them to the `script_list` variable for autocompletion.

**Comment by ethanwhite** [comment]
> From what you have mentioned it does feel feasible and I think I can add a function which would create these script names and store them somewhere, and then we can pass them to the script_list variable for autocompletion.

Yeah, looking at `display_all_rdataset_names` it seems like we could use very similar code to Lines 130-143 to generate that list. We just need to store instead of print and format the string as something like `f"rdataset-{package}-{dataset}`.

**Comment by Aakash3101** [comment]
> > From what you have mentioned it does feel feasible and I think I can add a function which would create these script names and store them somewhere, and then we can pass them to the script_list variable for autocompletion.
> 
> Yeah, looking at `display_all_rdataset_names` it seems like we could use very similar code to Lines 130-143 to generate that list. We just need to store instead of print and format the string as something like `f"rdataset-{package}-{dataset}`.

Exactly, that's what I was thinking

**Comment by ethanwhite** [comment]
> Exactly, that's what I was thinking

Nice! In that case I'd say give it a go if you don't think it will take too long to implement.

**Comment by Aakash3101** [comment]
Yeah for sure

**Comment by Aakash3101** [comment]
@ethanwhite @henrykironde I have made the changes requested by Ethan, the comments are also updated.

Comment 1: [link](https://github.com/weecology/retriever/pull/1613#issue-973655906)

Comment 2: [CLI examples](https://github.com/weecology/retriever/pull/1613#issuecomment-901278635)

**Comment by Aakash3101** [comment]
## Interface examples

1. `update_rdataset_catalog()`

This function creates/updates the `datasets_url.json` in the `~/.retriever/rdataset-scripts` directory. The `datasets_url.json` file contains all the details related to the Rdatasets. The information is fetched from the remote repository of Rdatasets.

```python
>>> import retriever as rt
>>> rt.update_rdataset_catalog()
```

2. `display_all_rdataset_names(package_name=None)`

This function prints the package, dataset name and the script name for the rdatasets present in the package(s) requested.
If no package is specified, it prints all the rdatasets, and if `all` is passed as the function argument then all the package names are displayed.

- displays the names of all the available Rdatasets
```python
>>> import retriever as rt
>>> rt.display_all_rdataset_names()         
List of all available Rdatasets

Package: aer              Dataset: affairs                   Script Name: rdataset-aer-affairs
Package: aer              Dataset: argentinacpi              Script Name: rdataset-aer-argentinacpi
Package: aer              Dataset: bankwages                 Script Name: rdataset-aer-bankwages
...
Package: vcd              Dataset: vonbort                   Script Name: rdataset-vcd-vonbort
Package: vcd              Dataset: weldondice                Script Name: rdataset-vcd-weldondice
Package: vcd              Dataset: womenqueue                Script Name: rdataset-vcd-womenqueue

```

- displays the names of all the Rdatasets present in the packages 'aer' and 'drc'
``` python
>>> rt.display_all_rdataset_names(['aer', 'drc'])
List of all available Rdatasets in packages: ['aer', 'drc']
Package: aer              Dataset: affairs                   Script Name: rdataset-aer-affairs
Package: aer              Dataset: argentinacpi              Script Name: rdataset-aer-argentinacpi
Package: aer              Dataset: bankwages                 Script Name: rdataset-aer-bankwages
...
Package: drc              Dataset: spinach                   Script Name: rdataset-drc-spinach
Package: drc              Dataset: terbuthylazin             Script Name: rdataset-drc-terbuthylazin
Package: drc              Dataset: vinclozolin               Script Name: rdataset-drc-vinclozolin

```

- displays all the packages present in Rdatasets
```python
>>> import retriever as rt
>>> rt.display_all_rdataset_names('all')
List of all the packages present in Rdatasets

aer         cluster   dragracer  fpp2     ggplot2movies  hsaur   lattice  mediation   multgee         plm    quantreg    sandwich   survival  
asaur       count     drc        gap      gt             hwde    lme4     mi          nycflights13    plyr   reshape2    sem        texmex    
boot        daag      ecdat      geepack  histdata       islr    lmec     mosaicdata  openintro       pscl   robustbase  stat2data  tidyr     
cardata     datasets  evir       ggplot2  hlmdiag        kmsurv  mass     mstate      palmerpenguins  psych  rpart       stevedata  vcd       
causaldata  dplyr     forecast

```

3. `update_rdataset_contents(data_obj, package, dataset_name, json_file)`

This function updates the json content of the Rdataset script created by `create_rdataset`.

```python
>>> import json
>>> import retriever as rt
>>> from retriever.lib.defaults import RDATASET_SCRIPT_WRITE_PATH
>>> data_obj = {
...     'csv': 'https://vincentarelbundock.github.io/Rdatasets/csv/drc/metals.csv',
...     'doc': 'https://vincentarelbundock.github.io/Rdatasets/doc/drc/metals.html',
...     'title': 'Data from heavy metal mixture experiments',
... }
>>> script_path = RDATASET_SCRIPT_WRITE_PATH
>>> script_filename = f"rdataset_{package}_{dataset_name}" + '.json'
>>> with open(f"{script_path}/{script_filename}", "r") as f:
...       json_file = json.load(f)
>>> f.close()
>>> package = 'drc'
>>> dataset_name = 'metals'
>>> json_file = rt.update_rdataset_contents(data_obj, package, dataset_name, json_file)

```

4. `update_rdataset_script(data_obj, dataset_name, package, script_path)`

This function renames and updates the content of the Rdataset script generated by `create_rdataset`. After renaming the
file, this function calls `update_rdataset_contents`, which returns the updated json object, then the new contents are 
written to the file.

```python
>>> import retriever as rt
>>> from retriever.lib.defaults import RDATASET_SCRIPT_WRITE_PATH
>>> data_obj = {
...     'csv': 'https://vincentarelbundock.github.io/Rdatasets/csv/drc/metals.csv',
...     'doc': 'https://vincentarelbundock.github.io/Rdatasets/doc/drc/metals.html',
...     'title': 'Data from heavy metal mixture experiments',
... }
>>> script_path = RDATASET_SCRIPT_WRITE_PATH
>>> package = 'drc'
>>> dataset_name = 'metals'
>>> rt.update_rdataset_script(data_obj, dataset_name, package, script_path)

```

5. `create_rdataset(engine, package, dataset_name, script_path=None)`

This function creates Rdataset scripts for retriever. First it downloads the raw data, then creates the script, 
and then updates it and at last, it installs the dataset using that script.

```python
>>> import retriever as rt
>>> from retriever.engines import choose_engine
>>> from retriever.lib.defaults import RDATASET_SCRIPT_WRITE_PATH
>>> 
>>> # engine = choose_engine({'command': 'install', 'engine': 'postgres'}) 
>>> # Every engine other than 'download' would download data, then create the script
>>> if the script does not exists, and then installs the dataset into the engine
>>> # Or
>>> engine = choose_engine({'command': 'download'})
>>> # The 'download' engine will just download the raw data files
>>> script_path = RDATASET_SCRIPT_WRITE_PATH
>>> package = 'drc'
>>> dataset_name = 'metals'
>>> rt.create_rdataset(engine, package, dataset_name, script_path)
Downloading metals.csv: 3.00B [00:00, 7.24B/s]                                                                                                    
>>> 

```

6. `get_rdataset_names()`

This functions returns the list of all the rdataset script names.

```python
>>> import retriever as rt
>>> script_names = rt.get_rdataset_names()
>>> print(script_names)
['rdataset-aer-affairs', 'rdataset-aer-argentinacpi', ....,
'rdataset-vcd-vonbort', 'rdataset-vcd-weldondice', 'rdataset-vcd-womenqueue']
```


7. Downloading a Rdataset
```python
>>> import retriever as rt
>>> rt.download('rdataset-drc-earthworms')
=> Downloading rdataset-drc-earthworms
Downloading earthworms.csv: 1.00B [00:00, 2.18B/s]
<retriever.engines.download_only.engine object at 0x7f6925aed590>
```

8. Installing a  Rdataset
```python
>>> import retriever as rt
>>> rt.install_postgres('rdataset-mass-galaxies')
Did you mean: 
	vertnet-mammals
=> Installing rdataset-mass-galaxies
Downloading galaxies.csv: 1.00B [00:00, 2.20B/s]
Processing... galaxies.csv
Successfully wrote scripts to /home/aakash01/.retriever/rdataset-scripts/galaxies.csv.json
Updating script name to rdataset-mass-galaxies.json
Updating the contents of script rdataset-mass-galaxies
Successfully updated rdataset_mass_galaxies.json
Updated the script rdataset-mass-galaxies
Creating database rdataset_mass_galaxies...

Installing rdataset_mass_galaxies.galaxies
Progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 82/82 [00:00<00:00, 2277.90rows/s]
<retriever.engines.postgres.engine object at 0x7f6925b4d7d0>

```

**Comment by ethanwhite** [comment]
Looks great! Thanks @Aakash3101!

**Comment by Aakash3101** [comment]
I am also adding the Rdatasets in the documentation like the `Datasets Available` section.

Screenshot from 2021-08-19 19-36-06

**Comment by henrykironde** [comment]
@Aakash3101, could you confirm the commands and the expected output. I have run a few commands and they are not working now. Something changed or its a problem on my system

```python
(testenv) ➜  retriever git:(test) ✗ retriever ls rdataset
usage: retriever [-h] [-v] [-q]
                 {download,install,defaults,update,new,autocreate,ls,citation,license,reset,help,commit,log}
                 ...
retriever: error: unrecognized arguments: rdataset
(testenv) ➜  retriever git:(test) ✗ retriever ls rdataset -h
usage: retriever ls [-h] [-l L [L ...]] [-k K [K ...]] [-v V [V ...]]
                    [-s S [S ...]]

optional arguments:
  -h, --help    show this help message and exit
  -l L [L ...]  search datasets with specific license(s)
  -k K [K ...]  search datasets with keyword(s)
  -v V [V ...]  verbose list of specified dataset(s)
  -s S [S ...]  search socrata datasets with name(s)
(testenv) ➜  retriever git:(test) ✗ retriever ls rdataset -p vcd                        
usage: retriever [-h] [-v] [-q]
                 {download,install,defaults,update,new,autocreate,ls,citation,license,reset,help,commit,log}
                 ...
retriever: error: unrecognized arguments: rdataset -p vcd

```

**Comment by Aakash3101** [comment]
@henrykironde did you install the PR on your system using `pip install . -U`. I will check this later and get back to you once I reach home.

**Comment by henrykironde** [comment]
Ah, yes, that could be an issue. I will try again later with the new command

**Comment by Aakash3101** [comment]
This is my output for the same commands that you ran:
Screenshot from 2021-08-22 00-29-03

**Comment by henrykironde** [comment]
Results 


```Python
(deepforest) ➜  retriever git:(test) ✗ retriever ls rdataset -p vcd aer
usage: retriever ls rdataset [-h] [-p P [P ...]] all
retriever ls rdataset: error: the following arguments are required: all
(deepforest) ➜  retriever git:(test) ✗ retriever ls rdataset -p vcd             
usage: retriever ls rdataset [-h] [-p P [P ...]] all
retriever ls rdataset: error: the following arguments are required: all
(deepforest) ➜  retriever git:(test) ✗ retriever ls rdataset all
List of all the packages present in Rdatasets

aer         cluster   dragracer  fpp2           gt  
```

**Comment by henrykironde** [comment]
Screen Shot 2021-08-21 at 4 14 56 PM

**Comment by Aakash3101** [comment]
Screenshot from 2021-08-22 01-55-39
Screenshot from 2021-08-22 01-55-32

**Comment by Aakash3101** [comment]
Could you show me your git log? and is your branch on the latest commit?

**Comment by henrykironde** [comment]
Sorry I was using an old commit. All works fine, thanks @Aakash3101 👍🏿

**Pull request merged**
