### PR TITLE
updated version for airports.json

### PR DESCRIPTION
**Pull request by ss-is-master-chief**
@henrykironde Please verify. Thank you

### CODE REVIEW

**Comment by henrykironde** [comment]
@ss-is-master-chief, have a look at the diff to confirm changes

**Comment by ss-is-master-chief** [comment]
@henrykironde The changes seem correct Sir.

**Comment by henrykironde** [comment]
Initially you had changed some thing in the scripts. Right now we only have changes on just the script version number and version.txt file.

**Comment by ss-is-master-chief** [comment]
@henrykironde Oh yes. The citation. Updated it.

**Comment by henrykironde** [comment]
Great Thanks for the update.

**Pull request merged**
