### PR TITLE
[WIP] Add BUPA Liver Disorders Dataset

### PR DESCRIPTION
**Pull request by ss-is-master-chief**
https://archive.ics.uci.edu/ml/datasets/Liver+Disorders

@henrykironde Please have a look

### CODE REVIEW

**Comment by henrykironde** [comment]
Update the branch you are working on. It seems you are using and old branch.

**Comment by ss-is-master-chief** [comment]
Done. Thanks!

**Comment by henrykironde** [comment]
@ss-is-master-chief, there are still some things that should not be there. In the version.txt file, we have changes that should not be there. 
Before you run the clean up. Do a `pip install . -U` in case you use Sudo `sudo pip install . -U`.
Lets try that.

**Comment by henrykironde** [comment]
Changes added to  #1150
Thanks @ss-is-master-chief, for this PR.

**Pull request closed without merging**
