### PR TITLE
fixes npn.py to get data of 3 months at a time

### PR DESCRIPTION
**Pull request by Parth-25m**
#693 
@henrykironde Continuation of #783 
Can you please provide the new version number ?

### CODE REVIEW

**Comment by henrykironde** [comment]
self.version = '1.0.1'. 
use `git commit --amend` when committing to this branch so that we keep one commit.
Also run `version.py` it will change/update the version number in `version.txt`.
Add version before committing.

**Comment by henrykironde** [comment]
@Parth-25m lets change the version number and run `version.py`.

before commit add `version.txt`

**Comment by henrykironde** [comment]
Sorry @Parth-25m, You need to clean  your repo. 
I suggest running

`retriever reset all`
`rm -r scripts`
`git reset --hard`
`python version.py`

This will give you the right `version.txt` to add and commit
if you do a git diff  before adding, you will see that the version file has only one line changes 
`npn.py,2.0.0` 

Then add and commit ammend

**Comment by ethanwhite** [comment]
Merged manually in 940b584 with a cleaned up version.txt.

Here's your official commit @Parth-25m:
https://github.com/weecology/retriever/commit/cf8eb841008e75b1593cc44db065e3ee55dfb140

Thanks so much for your contribution!

**Pull request closed without merging**
