### PR TITLE
Update format style in print

### PR DESCRIPTION
**Pull request by coolalexzb**
I updated the print statements mentioned in #1436 
E.g 
`print("\nDataset:  {}".format(dataset.name))`
to 
`print(f"\nDataset:  {dataset.name}")`

### CODE REVIEW

**Comment by henrykironde** [comment]
After a review, the best way would be to change every format to `fstring`.
- You can commit each file in a new commit to make it easy for review.
- The script directory can be left out since it may deal with backward compatibility with the old versions and the `retriever-recipes`.

**Comment by coolalexzb** [comment]
Actually, I checked all of the files of the project except files in script directory. All the print statements like `print("\nDataset: {}".format(dataset.name))` have been replaced. Do you mean that print statements like `print("Citation : %s", citation) `and `print("Citation : " + citation)` also need to be repalced?

**Comment by henrykironde** [comment]
Try to find other occurences using `grep -iR "format(" ./retriever`

**Comment by coolalexzb** [comment]
I forgot to pull the latest code before making a change. I will resolve conflicts after the mid term exams on Thursday. Sorry for the late submission.

**Comment by coolalexzb** [comment]
I make a change but it seems that there exists something wrong in travis CI build(permission problem in docker)

**Comment by coolalexzb** [comment]
Sorry for the late resubmit. I did not notice a little bug before.

**Comment by apoorvaeternity** [comment]
@coolalexzb It looks like there is some issue with your local git configuration because when you commit it doesn't point to a GitHub user. I think your commits are missing email.

**Comment by coolalexzb** [comment]
I commited with an email address. Can you check again? Thank you! @apoorvaeternity

**Comment by apoorvaeternity** [comment]
@coolalexzb Yep. The latest commit is correct.

**Comment by coolalexzb** [comment]
Ref #1462

**Pull request closed without merging**
