### PR TITLE
Change testdb name to testdb_retriever

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request aims to fix: #1243. It changes the name of `testdb` to `testdb_retriever` during testing.

### CODE REVIEW

**Comment by ashishpriyadarshiCIC** [comment]
@harshitbansal05  I'm not sure but I think you should also change the name at the Developers [docs](https://github.com/harshitbansal05/retriever/blob/change-testdb-name/docs/developer.rst) at the instruction for setting up PostgreSQL.

**Comment by harshitbansal05** [comment]
@ashishpriyadarshiCIC thanks for the review. I considered that but was not sure to do this in the same pr only. We can discuss this with the mentors.

**Comment by henrykironde** [comment]
Yes we should change that in the developer docs too as  @harshitbansal05 said

**Comment by harshitbansal05** [comment]
@henrykironde could you please review it now?

**Comment by henrykironde** [comment]
Rebase with master

**Comment by harshitbansal05** [comment]
@henrykironde Done.

**Comment by henrykironde** [comment]
👍 @harshitbansal05 for the PR. Looks great.

**Pull request merged**
