### PR TITLE
Kaggle support

### PR DESCRIPTION
**Pull request by DumbMachine**
#1465 had gotten stale, opened a new one.

### CODE REVIEW

**Comment by DumbMachine** [comment]
@henrykironde could you take a look here?

**Comment by henrykironde** [comment]
What error do you get when you test locally @DumbMachine

**Comment by DumbMachine** [comment]
None
```bash
(base) ➜  retriever git:(kaggle) ✗ pytest -k test_download_kaggle_dataset
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/weakstation/work/retriever, inifile: setup.cfg
plugins: doctestplus-0.5.0, astropy-header-0.1.2, hypothesis-5.5.4, arraydiff-0.3, openfiles-0.4.0, remotedata-0.3.2
collected 177 items / 174 deselected / 3 selected                              

test/test_retriever.py ...                                               [100%]

=============================== warnings summary ===============================
/home/weakstation/anaconda3/lib/python3.7/site-packages/retriever-2.4.1.dev0-py3.7.egg/retriever/lib/scripts.py:2
  /home/weakstation/anaconda3/lib/python3.7/site-packages/retriever-2.4.1.dev0-py3.7.egg/retriever/lib/scripts.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================= 3 passed, 174 deselected, 1 warning in 1.43s =================
(base) ➜  retriever git:(kaggle) ✗ 
```

**Comment by DumbMachine** [comment]
Travis seems to fail cuz of some other error:
```bash
PermissionError: [Errno 13] Permission denied: '/home/travis/build/weecology/retriever/cli_tools/postgis-data/12/main'
```

**Comment by henrykironde** [comment]
Okey, it seems like we are getting to the problem.
Also could you run these commands and report the output
```
flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90
yapf -d --recursive retriever/ --style=.style.yapf
```

**Comment by DumbMachine** [comment]
```bash
(base) ➜  retriever git:(kaggle) ✗ flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90
yapf -d --recursive retriever/ --style=.style.yapf
(base) ➜  retriever git:(kaggle) ✗ 
```

**Comment by henrykironde** [comment]
There is something wrong with your environment setup. What version of python are you using  
The same commands on your PR are giving me 

```j
retriever on  test [?] via 🐍 v3.7.6 
❯ yapf -d --recursive retriever/ --style=.style.yapf
--- retriever/lib/engine.py	(original)
+++ retriever/lib/engine.py	(reformatted)
@@ -506,11 +506,11 @@
         return True
 
     def download_from_kaggle(
-            self,
-            data_source,
-            dataset_name,
-            archive_dir,
-            archive_full_path,
+        self,
+        data_source,
+        dataset_name,
+        archive_dir,
+        archive_full_path,
     ):
         """Download files from Kaggle into the raw data directory"""
         kaggle_token = os.path.isfile(KAGGLE_TOKEN_PATH)
@@ -561,12 +561,12 @@
         return file_names
 
     def download_files_from_archive(
-            self,
-            url,
-            file_names=None,
-            archive_type="zip",
-            keep_in_dir=False,
-            archive_name=None,
+        self,
+        url,
+        file_names=None,
+        archive_type="zip",
+        keep_in_dir=False,
+        archive_name=None,
     ):
         """Download files from an archive into the raw data directory."""
         if not archive_name:
@@ -645,12 +645,12 @@
             excel_csv(src_path, path_to_csv, excel_info, encoding)
 
     def extract_gz(
-            self,
-            archive_path,
-            archivedir_write_path,
-            file_name=None,
-            open_archive_file=None,
-            archive=None,
+        self,
+        archive_path,
+        archivedir_write_path,
+        file_name=None,
+        open_archive_file=None,
+        archive=None,
     ):
         """Extract gz files.
 
@@ -994,12 +994,12 @@
         self.warnings.append(new_warning)
 
     def write_fileobject(
-            self,
-            archivedir_write_path,
-            file_name,
-            file_obj=None,
-            archive=None,
-            open_object=False,
+        self,
+        archivedir_write_path,
+        file_name,
+        file_obj=None,
+        archive=None,
+        open_object=False,
     ):
         """Write a file object from a archive object to a given path
 

retriever on  test [?] via 🐍 v3.7.6 took 4s 
❯ flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90
retriever/lib/datasets.py:21:35: E741 ambiguous variable name 'l'
retriever/lib/scripts.py:325:35: E741 ambiguous variable name 'l'
retriever/lib/scripts.py:326:13: E741 ambiguous variable name 'l'
```

**Comment by henrykironde** [comment]
Sorry let me  repost the errors, give me a minute

**Comment by henrykironde** [comment]
closing with ref https://github.com/weecology/retriever/commit/0705cc2215cfdc92adc55df3d47afb40308af98a

**Pull request closed without merging**
