### PR TITLE
GSoC: Add provenance and recipes

### PR DESCRIPTION
**Pull request by henrykironde**
GSoC2019: NumFOCUS

**1. Title: Data Retriever: Extract Scripts into Separate System**, @harshitbansal05

	Name: Harshit Bansal

**2. Title: Retriever Provenance**, @apoorvaeternity 

	Name: Apoorva Pandey
	

**MENTORS**

	Andrew Zhang
	Henry Senyondo
	Ethan White

### CODE REVIEW

**Comment by harshitbansal05** [comment]
Commands tested:
1. `retriever ls`:

Screenshot from 2019-08-24 01-18-34

2. `retriever ls` after deleting a dataset:

Screenshot from 2019-08-24 01-19-14

3. `retriever citation` for a deleted dataset:

Screenshot from 2019-08-24 01-20-36

4. `retriever ls -l MIT` (which searches upstream scripts as well):

Screenshot from 2019-08-24 01-21-39

**Comment by harshitbansal05** [comment]
Some more commands tested:

1. Installation of a deleted script:

Screenshot from 2019-08-24 01-30-18


2. Version prompt if a newer version of the script is present upstream:

Screenshot from 2019-08-24 01-32-39

**Comment by harshitbansal05** [comment]
@henrykironde @zhangcandrew some screenshots of the tested commands ^

**Comment by apoorvaeternity** [comment]
Some tested commands:
https://github.com/weecology/retriever/issues/1378#issuecomment-524561930

**Comment by apoorvaeternity** [comment]
### Tested command `retriever-recipes new_json`
Screenshot 2019-08-24 at 9 56 08 PM
Worked as expected. Just don't know why Encoding was asked twice. @harshitbansal05 is looking into it.


### Tested command `retriever-recipes edit_json`
Screenshot 2019-08-24 at 9 53 16 PM
Worked as expected.

### Tested command `retriever-recipes delete_json`
Screenshot 2019-08-24 at 10 05 16 PM
Worked as expected.
@henrykironde @harshitbansal05

**Comment by harshitbansal05** [comment]
The PR for the encoding bug: https://github.com/weecology/retriever-recipes/pull/29. @apoorvaeternity @henrykironde.

**Comment by henrykironde** [comment]
A big thank you to @zhangcandrew who was a big part of making this PR happen and putting time aside for the project.
Thank you to @harshitbansal05  and @apoorvaeternity for the work on this PR and @ethanwhite  for leading the way forward and providing input on the project's design.

**Comment by ethanwhite** [comment]
Fantastic work everyone! :tada: :tada: :tada: Like @henrykironde I'm super excited by the awesome work accomplished by @harshitbansal05 & @apoorvaeternity over the summer and very thankful both the awesome mentoring by @zhangcandrew & @henrykironde as well. You should all be super proud of what you've accomplished.

**Comment by zhangcandrew** [comment]
Honestly some really incredible work! Almost 2000 lines of code touched!!!! These are some pretty big improvements for retriever and I think they really solidify its ability to scale up and take on a whole new form! 

Thanks to @harshitbansal05 and @apoorvaeternity  for dedicating your summers working on our open source project and pushing retriever forward. And a huge thanks to @henrykironde and @ethanwhite for making this all possible and being my own mentors along the way. :)

**Pull request merged**
