### PR TITLE
Fix encoding issue in python interface

### LINKED ISSUE #1097: Python 2 encoding issues in Python interface only
In the Python interface some datasets (at least `airports` and `gentry-forest-transects`) report encoding issues and fail. E.g.,

```
In [11]: rt.install_sqlite('gentry-forest-transects')
=> Installing gentry-forest-transects
'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
```

But these same datasets install fine from the CLI.

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Fixes #1097

### CODE REVIEW

**Comment by henrykironde** [comment]
@zhangcandrew, this looks to good to me. 
I have not been able to recreate the error on Mac python 2., can you test.

**Comment by apoorvaeternity** [comment]
@henrykironde I added unicode characters in citation and tested in CLI and it worked fine.

**Comment by zhangcandrew** [comment]
Tested it out on a few datasets, and I can't seem to reproduce the error on Python2.7 or Python3.5. 

Looks good to me!

**Comment by henrykironde** [comment]
LGTM, ..merge

**Pull request merged**
