### PR TITLE
Kaggle support

### PR DESCRIPTION
**Pull request by DumbMachine**
Reopened #1426 1426

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @DumbMachine , like we discussed yesterday, always make sure this PR is up to date with upstream master .  Clean up the commit history to have one commit. In case you need help, let me know. For now, I will go through the logic as you clean it up.

**Comment by DumbMachine** [comment]
Do not know how the versions.txt updated, I will undo that change

**Comment by henrykironde** [comment]
@DumbMachine thanks for making these changes 👍, squash all the commits to one commit and make sure the branch is up to date with master

**Comment by henrykironde** [comment]
We shall still need only one commit. Let me know if you need help with that

When it comes to the tests failing, we added some testing on the style.
For example, we require code to be of given length (--max-line-length=90)
You can run these tool to see what needs to be changed. 
  
```
flake8 --ignore=E501,W503,E402,F401,F403,E722,F841,W504 retriever --max-line-length=90
pylint -rn retriever/ -f colorized --rcfile=.pylintrc
yapf --recursive retriever/ --style=.style.yapf -i
```

**Comment by DumbMachine** [comment]
image
I don't seem to be getting the errors in my local repo.

**Comment by henrykironde** [comment]
Run `pip uninstall retriever` several times until you make sure that there is no retriever .
Then install `pip using pip install . -U`
And run those functions again.

**Comment by DumbMachine** [comment]
> Run pip uninstall retriever several times until you make sure that there is no retriever .
Then install pip using pip install . -U
And run those functions again.

image

**Comment by henrykironde** [comment]
If you have time to zoom in let me know

**Comment by ethanwhite** [comment]
Replaced by #1491.

**Pull request closed without merging**
