### PR TITLE
WIP: Add script for eBird Observation Data

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by ethanwhite** [comment]
This code has not yet been tested.

**Comment by ethanwhite** [comment]
Here you go @akshayah3. Testing and improvements would be most welcome. Thanks!

**Comment by akshayah3** [comment]
@ethanwhite I was just about to send the PR regarding this! My code and yours look the same actually :)

**Comment by ethanwhite** [comment]
Ah, in that case why don't you go ahead and send the PR and I'll close this one.

**Pull request closed without merging**
