### PR TITLE
Corrects very minor typo error

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request corrects a very minor typo error.

### CODE REVIEW

**Comment by harshitbansal05** [comment]
@henrykironde, I don't quite understand the Travis log. Could you please help?

**Comment by henrykironde** [comment]
https://github.com/psycopg/psycopg2/releases made a release 2 days ago that is why we failing.
I will look into it later.

**Comment by henrykironde** [comment]
@harshitbansal05 thanks for catching this. This looks good to go in after I make sure that psycopg2 can install

**Comment by henrykironde** [comment]
@harshitbansal05 thanks for this.

**Pull request merged**
