### PR TITLE
add py.test and remove nose test fixes #404

### LINKED ISSUE #404: Switch to pytest for testing
nose is no longer being developed and the consensus replacement is [pytest](http://pytest.org/latest/).

### PR DESCRIPTION
**Pull request by henrykironde**
no environment variables explicitly set (tox.ini). [ref](https://github.com/codecov/example-python)

### CODE REVIEW

**Comment by ethanwhite** [comment]
So does this pass mean we're all set for merge. That was more straight forward than I'd been assuming.

**Comment by henrykironde** [comment]
@ethanwhite, we cant merge. 
The tests work fine however the coverage report is what we are not getting right. Codecov is not performing as expected.
I am assuming two things,

1. The path setting is not right
2. or we are right and pytest only reports the files that have been hit (which case I assume is a false hypothesis) 

This is the [report](https://codecov.io/github/weecology/retriever?pr=446) to our current PR.
 and basically only the lib folder is shown which is not the case with the [old reports](https://codecov.io/github/weecology/retriever?pr=445) that show the whole repo tree

**Comment by ethanwhite** [comment]
@henrykironde - got it. Let me know when you think everything is working and I'll take a look.

**Comment by henrykironde** [comment]
pytest runs well. 
The cov report here is a little different from the cov report when using nose.
With pytest , they do not report files that are not hit by the tests and hence some files don't show up.

**Comment by ethanwhite** [comment]
Is the addition to the slack secure line intentional? Looks like it might be an accidental copy/paste.

**Comment by ethanwhite** [comment]
Thanks for switching that back @henrykironde. Let's go ahead and officially make the move to pytest.

**Comment by henrykironde** [comment]
@ethanwhite copy and paste never a good way :+1:

**Pull request merged**
