### PR TITLE
Update pyretriever.rst

### PR DESCRIPTION
**Pull request by ss-is-master-chief**
Added output to `check_for_updates()`

### CODE REVIEW

**Comment by henrykironde** [comment]
looks good. remove one file `docs/datasets.rst`

**Comment by ss-is-master-chief** [comment]
@henrykironde Yes for sure Sir. But wouldn't it be good if we left the index of the datasets intact for now and remove it later. Since it serves as a list from where we can look into the datasets themselves.

For now there are 84 existing data-sets but `datasets.rst` has only 82. The ones which are missing are : `airports` and `+1`.

Should I go ahead and still remove it?

**Comment by henrykironde** [comment]
That was added by mistake. That file is supposed to be created at run time when you build the docs `make html`. 
`Make` will run docs/conf.py`. The current name for the file is `datasets_list.rst`.  Previously, it was `datasets.rst`. None of those files should be committed.

if you noticed, your current build will show some warning as below
```bash
(venv35) ~\Documents\GitHub\retriever\docs [t1058 +1 ~0 -0 !]> make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: 15 added, 0 changed, 0 removed
reading sources... [100%] scripts
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\Users\Henry\Documents\GitHub\retriever\docs\datasets.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] scripts
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.

```

**Comment by ss-is-master-chief** [comment]
@henrykironde I'll issue a PR to delete `datasets.rst` right away. Thank you for the clarification.

**Comment by henrykironde** [comment]
Okey I am merging this

**Pull request merged**
