### PR TITLE
Verbose mode for dataset display using 'retriever ls'

### PR DESCRIPTION
**Pull request by goelakash**
#210 
Screenshot:

1. without `-l` flag
selection_009

2.  with `-l` flag for verbose output
selection_010

@ethanwhite @henrykironde

### CODE REVIEW

**Comment by henrykironde** [comment]
This is Great @goelakash, 
I want us to envision a case where we have a lot of data sets, how can we effectively display the information. One way could be sorting alphabetically based on some variables, ie. tags (list based on some grouping like plants ) or citation ....

We could present this PR changes as the default display of results and then if a person gives an optional flag
for example`` retriever ls -l `` could display the data based on some criteria.

**Comment by ethanwhite** [comment]
Thanks @goelakash! I like the idea of keeping the current compressed output with `retriever ls` and this longer form with more detail with `retriever ls -l` (very analogous to the behavior of `ls` itself).

I also like the idea of being able to filter based on tags, e.g., `retriever ls fish` and `retriever ls -l fish` just showing the outputs for datasets containing the `fish` tag. (this part could definitely be a separate PR if you preferred).

**Comment by henrykironde** [comment]
looks good, just let me know if you plan to add anything

**Comment by goelakash** [comment]
@henrykironde  Added extension to search with keywords.

**Pull request merged**
