### PR TITLE
Fixed - Update scripts to datapackage.JSON standard

### PR DESCRIPTION
**Pull request by goelakash**
new PR with fixes for merge conflicts in the previous [PR](https://github.com/weecology/retriever/pull/606)

### CODE REVIEW

**Comment by henrykironde** [comment]
Am testing this, Will let you know.

**Comment by goelakash** [comment]
@henrykironde Any issues?

**Comment by henrykironde** [comment]
@goelakash still testing, taking a lunch break. 
but so far everything looks good.
I was trying to also add some testings for encoded strings

simple_csv = {'name': 'simple_csv',
              'raw_data': "a,b,c\nLöve & D. Löve,2,3\n4,5,6\n",
              'script': "shortname: simple_csv\ntable: simple_csv, http://example.com/simple_csv.txt",
              'expect_out': 'a,b,c\nLöve & D. Löve,2,3\n4,5,6\n'}
if you want have time you could look at it and give it a try. will be back in a an hour or two

**Comment by henrykironde** [comment]
give me like three hours will get back to you

**Comment by goelakash** [comment]
@henrykironde Yeah, that does not pass, even in `master`.

**Comment by henrykironde** [comment]
Does not work on python3

**Comment by goelakash** [comment]
@henrykironde This issue is not pertinent to this PR. It exists in `master` as well. I will send a PR in a couple of days to rectify this.

**Comment by ethanwhite** [comment]
I agree with @goelakash that the Python 3 issue for that test should be a separate PR and shouldn't block getting this one in.

**Pull request merged**
