### PR TITLE
Added Raymond2011 script to retriever

### PR DESCRIPTION
**Pull request by zhangcandrew**
Added the Raymond2011 script to retriever.

The UTF-8 encoding issue no longer appears. There is a new issue which pops up when trying to install this file. All of them deal with the 'Isotope' table in Raymond2011. The errors shows up as: 
```
WARNING (Raymond2011:isotopes): Exception in line 1755: invalid literal for int() with base 10: 'Antarctic silverfish'
```

Part of issue #732

### CODE REVIEW

**Comment by henrykironde** [comment]
This is solved in the the current PR #744, but we can wait for the merge the PR(744).
I am left with the zip python3 problem which is 95% solved. Only clean up and testing will be left.

@zhangcandrew, for the scripts from ML I tested them and they were passing. I recommend preparing a PR and sending it in. If you want to test the scripts use the `Only for testing all PRs #746` I bet Today after after noon we shall have these changes into master

**Comment by ethanwhite** [comment]
@zhangcandrew is there a reason you closed this or this ready to be merged?

**Comment by zhangcandrew** [comment]
Raymond2011 is part of the larger Ecological Archive we hope to have in for 2.0. We were having issues with it before, but I think it was solved on @henrykironde's new branch. Everything loads into the tables properly for Raymond2011, so I think it's good to stay closed. I'm not sure why it says I closed it, but henry closed it at the end of issue #732.

**Comment by ethanwhite** [comment]
Ah, got it. Thanks.

**Pull request closed without merging**
