### PR TITLE
Refactor code for provenance features

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Improve code based on the reviews on #1374

### CODE REVIEW

**Comment by henrykironde** [comment]
Organize the imports 
```python
import json
import os
from collections import OrderedDict
from datetime import datetime, timezone
from importlib import util
from shutil import rmtree
from tempfile import mkdtemp
from zipfile import ZipFile

import pkg_resources

from retriever.engines import choose_engine
from retriever.lib.datasets import datasets
from retriever.lib.defaults import HOME_DIR, ENCODING, PROVENANCE_DIR
from retriever.lib.engine_tools import getmd5
from retriever.lib.load_json import read_json
```

Add a line before def get_script(path_to_archive):

And make sure line length is not more that 90

**Comment by apoorvaeternity** [comment]
@henrykironde Sometimes when the code becomes nested it becomes too difficult to get it under 90 characters while having self-explanatory variable names.
Also, sometimes if I try to break a line into multiple lines it makes the code look weird.

**Comment by apoorvaeternity** [comment]
@henrykironde Made the changes. None of the lines is above 90 characters now.

**Comment by henrykironde** [comment]
This looks good, I am going to post some of what I have and you could reference where you feel we could improve.

**Comment by henrykironde** [comment]
```python
def commit_info_for_installation(metadata_info):
    """
    Returns a dictionary with commit info and changes in old and current environment
    """
    info = {
        "commit_message": metadata_info["commit_message"],
        "time": metadata_info["time"],
        "package_not_found": {},
        "package_changed": {},
    }
    old_package_details = metadata_info["packages"]
    current_package_details = package_details()

    if not metadata_info["packages"] == package_details():
        for package in old_package_details:
            old = old_package_details[package]
            cur = current_package_details[package]

            if package not in current_package_details:
                info["package_not_found"] = {package: old}
            elif old != cur:
                info["package_changed"] = {package: {"old": old, "current": cur}}
    return info


def installation_details(metadata_info, quiet):
    """
    Outputs details of the commit for eg. commit message, time,
    changes in environment
    """
    details = commit_info_for_installation(metadata_info=metadata_info)
    if not quiet:
        print("Commit Message:", details["commit_message"])
        print("Time:", details["time"])
        if details["package_not_found"] or details["package_changed"]:
            print(
                "The following requirements are not met.\n"
                "The installation may fail or not produce required results."
            )
            if details["package_not_found"]:
                print("The following packages were not found:")
                for package in details["package_not_found"]:
                    print(
                        "{}=={}".format(package, details["package_not_found"][package])
                    )
            if details["package_changed"]:
                print("The following packages have different versions:")
                for package in details['package_changed']:
                    old_version = details['package_changed'][package]['old']
                    current_version = details['package_changed'][package]['current']
                    message = "Required: {0}=={1}  Found: {0}=={2}"
                    print(message.format(package, old_version, current_version))


def get_script(path_to_archive):
    """
    Reads script from archive.
    """
    with ZipFile(os.path.normpath(path_to_archive), "r") as archive:
        try:
            commit_details = get_metadata(path_to_archive=path_to_archive)
            workdir = mkdtemp(dir=os.path.dirname(path_to_archive))
            archive.extract(
                "/".join(("script", commit_details["script_name"])), workdir
            )
            if commit_details["script_name"].endswith(".json"):
                script_object = read_json(
                    os.path.join(
                        workdir, "script", commit_details["script_name"].split(".")[0]
                    )
                )
            elif commit_details["script_name"].endswith(".py"):
                spec = util.spec_from_file_location(
                    "script_module",
                    os.path.join(workdir, "script", commit_details["script_name"]),
                )
                script_module = util.module_from_spec(spec)
                spec.loader.exec_module(script_module)
                script_object = script_module.SCRIPT
            rmtree(workdir)
        except Exception as e:
            print(e)
            return
        return script_object


def install_committed(path_to_archive, engine, force=False, quiet=False):
    """
    Installs the committed dataset
    """
    with ZipFile(os.path.normpath(path_to_archive), "r") as archive:
        try:
            workdir = mkdtemp(dir=os.path.dirname(path_to_archive))
            engine.data_path = os.path.join(workdir)
            script_object = get_script(path_to_archive=path_to_archive)
            metadata_info = get_metadata(path_to_archive=path_to_archive)
            installation_details(metadata_info=metadata_info, quiet=quiet)
            if not force:
                confirm = input(
                    "Please enter either y to continue with installation or n to exit:"
                )
                while not (confirm.lower() in ["y", "n"]):
                    print("Please enter either y or n:")
                    confirm = input()
            else:
                confirm = "y"
            if confirm.lower() == "y":
                for filename in archive.namelist():
                    if filename.startswith(script_object.name + "/"):
                        archive.extract(filename, workdir)
                engine.script_table_registry = OrderedDict()
                script_object.download(engine)
        except Exception as e:
            print(e)
            return
        finally:
            engine.data_path = None
            rmtree(workdir)
        return engine


def commit_log(dataset):
    """
    Shows logs for a committed dataset which is in provenance directory
    """
    try:
        committed_dataset_path = os.path.join(PROVENANCE_DIR, dataset)
        if os.path.exists(committed_dataset_path):
            log = {}
            for root, _, files in os.walk(committed_dataset_path):
                # generator with a list of all .zip files
                gen = (file for file in files if file.endswith(".zip"))
                for file in gen:
                    commit_info = get_metadata(path_to_archive=os.path.join(root, file))
                    commit_datetime = datetime.strptime(
                        commit_info["time"], "%m/%d/%Y, %H:%M:%S"
                    )
                    log[commit_datetime] = (
                        commit_info["commit_message"],
                        "{}{}".format(
                            commit_info["md5_dataset"][:3],
                            commit_info["md5_script"][:3],
                        ),
                    )
            # sort the commits according to time in reverse order i.e.
            # latest commit is the first element
            sorted_log = sorted(log.items(), reverse=True)
            for commit_value in sorted_log:
                print("\nCommit message:", commit_value[1][0])
                print("Hash:", commit_value[1][1])
                print("Date:", commit_value[0].strftime("%m/%d/%Y, %H:%M:%S"))
        else:
            print("No logs for {}".format(dataset))
    except Exception as e:
        print("Unable to generate log for", dataset)
        print(e)

```

**Comment by henrykironde** [comment]
Update what you feel could make a difference. Otherwise I could just go ahead and review what we have now.

**Comment by apoorvaeternity** [comment]
@henrykironde Made some more improvements based on your input. Ready for a review.

**Pull request merged**
