### PR TITLE
Add scripts from EA archive 2000 to 2011

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
These scripts are still undergoing testing. Feel free to jump in and comment or test some

**Comment by ethanwhite** [comment]
I haven't look at these more closely, but is there a reason we need the `.script` files?

**Comment by henrykironde** [comment]
@ethanwhite I thought we needed them, will go ahead and remove them

**Comment by ethanwhite** [comment]
Sorry for the confusion. Since these are new scripts the old versions of the retriever will all ignore them anyway, so nothing to worry about there.

**Comment by goelakash** [comment]
@henrykironde Were these JSON scripts made using the CLI, or converted from .script files by the parser function?

**Comment by henrykironde** [comment]
They were converted from .script files by the parser function.
They are not ready for merging because they still have unicode issues.

**Pull request closed without merging**
