### PR TITLE
added citation for nd-gain.json

### PR DESCRIPTION
**Pull request by ss-is-master-chief**
@henrykironde Please have a look

### CODE REVIEW

**Comment by henrykironde** [comment]
@ethanwhite, would you take a look
https://scholar.google.com/scholar?cluster=7258194722130698869&hl=en&as_sdt=0,10&sciodt=0,10

**Comment by ethanwhite** [comment]
@henrykironde - yeah, I think that's the right thing to cite.

@ss-is-master-chief - here's the full citation:

Chen, C., Noble, I., Hellmann, J., Coffee, J., Murillo, M. and Chawla, N., 2015. University of Notre Dame Global Adaptation Index Country Index Technical Report. ND-GAIN: South Bend, IN, USA.

**Comment by ss-is-master-chief** [comment]
@henrykironde @ethanwhite I have made the changes. But is that the full citation? There's a list of contributing experts on page 1 and 2 of the technical document.

**Comment by henrykironde** [comment]
That is okey. squash the commits and update the version.txt

**Comment by ss-is-master-chief** [comment]
The main repo doesn't seem to contain `nd-gain.py`. Is that why TravisCI is failing it?

**Comment by henrykironde** [comment]
You can restart a build on travis. that's what I just did

**Comment by ss-is-master-chief** [comment]
@henrykironde Thank you

**Comment by henrykironde** [comment]
@ss-is-master-chief, this looks great. let'r us remove this line "encoding": "UTF-8". Unless encoding is really needed we do not have to  provide it.


We should also remove the same from other scripts:

```
 airports
 breed-bird-survey-nlcd
 gdp
 nd-gain
```

**Comment by henrykironde** [comment]
@ss-is-master-chief, You need to update your branch because we have new updates for this file from 23d0b9e96a6ce5ce8609f83eb18cc363e975348e

**Comment by ss-is-master-chief** [comment]
@henrykironde @zhangcandrew @ethanwhite Please have a look at the changes.

**Comment by henrykironde** [comment]
Thanks @ss-is-master-chief, merging

**Pull request merged**
