### PR TITLE
Fixes #1570

### LINKED ISSUE #1570: retriever ls -v command does not work
While executing the ```retriever ls -v``` command, output is incorrect due to ```IndexError: list index out of range```.
Possible reasons are that some dataset json files have no license field or the license field is empty.
```
aakash01@aakash01-G3-3579:~/Desktop/gsoc/retriever (main)$ retriever ls -v
Offline datasets : 251

1. Abalone Age and Size Data
 abalone-age
[]
Database to aid in the prediction of the age of an Abalone given physical measurements
None
Lichman, M. (2013). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

2. Long term limnological measures in Acton Lake, database, 1992-2017
 acton-lake
['lake', 'stream', 'nutrients', 'nitrogen', 'phosphorus', 'chlorophyll', 'LTREB', 'long-term', 'ecosystem', 'ammonium-nitrogen', 'nitrate-N', 'oxygen', 'carbon']
Long-term data collected from Acton Lake and its inflow streams, on a suite of physical, chemical and biological variables investigating how Acton Lake, responds to changes in ecosystem subsidies of detritus (sediments) and nutrients.
None
Michael J Vanni, Maria J Gonzalez, and William H Renwick. 2019. Long term limnological measures in Acton Lake, a southwest Ohio reservoir, and its inflow streams: 1992-2017. Environmental Data Initiative.

Traceback (most recent call last):
  File "/home/aakash01/anaconda3/envs/gsoc-dev/bin/retriever", line 8, in <module>
    sys.exit(main())
  File "/home/aakash01/anaconda3/envs/gsoc-dev/lib/python3.7/site-packages/retriever/__main__.py", line 150, in main
    licenses=str(script.licenses[0]['name']),
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by Aakash3101**
Fixes the IndexError in license name for the ```retriever ls -v``` command

### CODE REVIEW

**Comment by henrykironde** [comment]
This looks like a good check that we could add to catch those kinds of errors. Let me check something out and get back to you

**Comment by Aakash3101** [comment]
> This looks like a good check that we could add to catch those kinds of errors. Let me check something out and get back to you

Sure

**Comment by Aakash3101** [comment]
@henrykironde Can you please rerun the checks on this PR, I see a postgres error in the failed check. All the tests passed on my local machine.

**Comment by henrykironde** [comment]
@Aakash3101  Could you try to find the corresponding python interface for the options we can provide with `retriever ls` below
That is retriever  
```j
-l L [L ...]    search datasets with specific license(s)
-k K [K ...]    search datasets with keyword(s)
-v [V [V ...]]  verbose list of all datasets 
```
A starting point is `retriever ls` CLI is similar to 

```python
>>> import retriever as rt
>>> rt.dataset_names()
```

 `retriever ls -l MIT` CLI is similar to


```python
NameError: name 'datasets' is not defined
>>> import retriever as rt
>>> rt.datasets(licenses="MIT")

```

**Comment by Aakash3101** [comment]
So for the ```retriever ls``` command, the three options available are ```-l```, ```-k``` and ```-v``` for displaying the datasets with the specified license(s), keyword(s) and dataset name(s).

```retriever ls -l MIT``` is similiar to 
```
>>> import retriever as rt
>>> rt.datasets(licenses="MIT")
```

```retriever ls -k airports``` is similiar to 
```
>>> import retriever as rt
>>> rt.datasets(keywords="airports")
```
and ```retriever ls -v <dataset-name>``` currently has no implementation in the python interface in the ```retriever.lib.datasets.py```.

**Comment by Aakash3101** [comment]
Following are the outputs of the function ```dataset_verbose_list```

```python
>>> from retriever.lib.datasets import dataset_verbose_list
>>> dataset_verbose_list(["airports", "abalone-age", "acton-lake"])
1. Dataset containing information on all airports on ouraiports.com
Dataset Name: airports
Keywords: ['airports', 'aeroplanes', 'airplanes', 'frequencies', 'runways', 'navaids', 'countries', 'regions']
Description: Dataset containing information on all airports on ourairports.com
Licenses: None
Citation: OurAirports.com, Megginson Technologies Ltd.

2. Abalone Age and Size Data
Dataset Name: abalone-age
Keywords: []
Description: Database to aid in the prediction of the age of an Abalone given physical measurements
Licenses: None
Citation: Lichman, M. (2013). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

3. Long term limnological measures in Acton Lake, database, 1992-2017
Dataset Name: acton-lake
Keywords: ['lake', 'stream', 'nutrients', 'nitrogen', 'phosphorus', 'chlorophyll', 'LTREB', 'long-term', 'ecosystem', 'ammonium-nitrogen', 'nitrate-N', 'oxygen', 'carbon']
Description: Long-term data collected from Acton Lake and its inflow streams, on a suite of physical, chemical and biological variables investigating how Acton Lake, responds to changes in ecosystem subsidies of detritus (sediments) and nutrients.
Licenses: None
Citation: Michael J Vanni, Maria J Gonzalez, and William H Renwick. 2019. Long term limnological measures in Acton Lake, a southwest Ohio reservoir, and its inflow streams: 1992-2017. Environmental Data Initiative.

>>> dataset_verbose_list(["airports", "abalone-age", "acton-lak"])
Dataset(s) is not found
>>> dataset_verbose_list(["airports"])
1. Dataset containing information on all airports on ouraiports.com
Dataset Name: airports
Keywords: ['airports', 'aeroplanes', 'airplanes', 'frequencies', 'runways', 'navaids', 'countries', 'regions']
Description: Dataset containing information on all airports on ourairports.com
Licenses: None
Citation: OurAirports.com, Megginson Technologies Ltd.

```

**Comment by Aakash3101** [comment]
@henrykironde Can you please rerun the checks on the PR? Also can you explain why these checks fail due to some ```debconf``` error. Its the 2nd time these checks have failed on my commit. But all tests pass on my local machine.

**Comment by henrykironde** [comment]
Separate this PR into two
1. For only changes in get_opts file
2. The other changes other than those in get_opts

**Comment by Aakash3101** [comment]
Okay @henrykironde

**Pull request closed without merging**
