### PR TITLE
BBS file capitalization (fix #548)

### PR DESCRIPTION
**Pull request by davharris**
fix #548

### CODE REVIEW

**Comment by davharris** [comment]
On my machine, the problem seems to persist even when I use this branch (in the sense that I use `pip install git+https://github.com/davharris/retriever.git@Ww`).

Am I using the wrong command, or is the problem not actually fixed?

**Comment by ethanwhite** [comment]
You probably need to do:

retriever reset scripts
retriever update

To get the new script since this is on master.

**Comment by davharris** [comment]
I'm not sure I understand.  It's not on master yet? Or did you mean that I should wait until this gets merged and it will work then?

**Comment by ethanwhite** [comment]
Ah yes, sorry.

So, to test changes to scripts you need to do a couple of things, but one of them isn't actually reinstalling the retriever (because it reads the scripts independently of the installed version so that we can make quick fixes for changes like this).

1. Remove the old script, most easily done with `git reset scripts` (this shouldn't be necessary but we have an order of operations issue to solve).
2. Run the retriever from inside the local repository where the updated script is. This way it can see the new script file in the `script/` directory.

Let me know if that's what you needed.

**Comment by davharris** [comment]
Thanks Ethan.  Still no luck though.  I can run `retriever install postgres BBS` from the `retriever` directory or from `retriever/scripts` subdirectory and still get the same error. Sorry if I'm just being dense!

**Comment by henrykironde** [comment]
no @davharris every thing is practically failing.
I am trying to work around it. I tried all engines and for now what I can say is, the problem comes from  the insert bulk code.

**Comment by henrykironde** [comment]
I think you found a Gem bug, making development/enhancement of tests the main priority

**Comment by ethanwhite** [comment]
This PR works fine for me up until the warnings mentioned in #460. Ubuntu 15.04, Python 2.7.11. See output below.

Happy to take a look at what's going on on other folks machines until my non-stop day of meetings starts at 9:30 am.

```
ethan@croryx:~/RetrieverCode (master)$ retriever reset all
This will remove existing scripts, cached data, and information on database connections. Specifically it will remove the scripts and raw_data folders and the connections.config file in /home/ethan/.retriever/. Do you want to proceed? (y/N)
y
ethan@croryx:~/RetrieverCode (master)$ git checkout pr/459 
Branch pr/459 set up to track remote branch pr/459 from upstream.
Switched to a new branch 'pr/459'
ethan@croryx:~/RetrieverCode (pr/459)$ pip install . --upgrade
Processing /home/ethan/Dropbox/Informatics/Retriever/src
Requirement already up-to-date: xlrd in /home/ethan/anaconda/lib/python2.7/site-packages (from retriever===1.9.0-de)
Installing collected packages: retriever
  Found existing installation: retriever 1.9.0-de
    Uninstalling retriever-1.9.0-de:
      Successfully uninstalled retriever-1.9.0-de
  Running setup.py install for retriever ... done
Successfully installed retriever-1.9.0-de
You are using pip version 8.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ethan@croryx:~/RetrieverCode (pr/459)$ retriever install sqlite BBS
=> Installing USGS North American Breeding Bird Survey
Creating table BBS_species...
Saving a copy of SpeciesList.txt...
Downloading SpeciesList.txt...
Inserting rows to BBS_species: 749 / 749
Downloading /home/ethan/.retriever/raw_data/BBS/Routes.zip...
Cleaning routes data...
Creating table BBS_routes...
Inserting rows to BBS_routes: 5627 / 5627
Downloading /home/ethan/.retriever/raw_data/BBS/Weather.zip...
Cleaning weather data...
Creating table BBS_weather...
Inserting rows to BBS_weather: 116093 / 116093
Creating table BBS_region_codes...
Saving a copy of RegionCodes.txt...
Downloading RegionCodes.txt...
Inserting rows to BBS_region_codes: 63 / 63
Creating table BBS_counts...
Inserting data from Alabama...
Downloading /home/ethan/.retriever/raw_data/BBS/Alabama.zip...
Inserting data from Alaska...
Downloading /home/ethan/.retriever/raw_data/BBS/Alaska.zip...
Inserting data from Arizona...
...
Downloading /home/ethan/.retriever/raw_data/BBS/Quebec.zip...
Inserting data from Saskatchewan...
Downloading /home/ethan/.retriever/raw_data/BBS/Saskatc.zip...
Inserting data from Yukon...
Downloading /home/ethan/.retriever/raw_data/BBS/Yukon.zip...
WARNING (BBS:species): Exception in line 1: invalid literal for int() with base 10: 'Seq'
WARNING (BBS:species): Exception in line 2: invalid literal for int() with base 10: '------'
Done!
```

**Pull request merged**
