### PR TITLE
Added file logger

### LINKED ISSUE #151: Log errors and other issues
We should use the `logging` module to log anything that gets caught in an except statement during a Retriever session. This can then be used to help with debugging errors, in particular those that we can't replicate locally.

### PR DESCRIPTION
**Pull request by piyushchauhan**
Fixes #151 
Made file logger using `logging` module and used it for as many exceptions as possible.

### CODE REVIEW

**Comment by henrykironde** [comment]
Could you update your branch with master.
I think we should limit loggers to only areas where we expect some catastrophic failures. I am against all if statements having a logger.

**Comment by henrykironde** [comment]
Lets not have loggers in the scripts directory and test directory

**Comment by henrykironde** [comment]
Something worth reading through would be the last PR comments, In the Issue page there are two PR's that tried to solve this problem

**Comment by harshitbansal05** [comment]
@piyushchauhan if possible can I contribute to it?

**Comment by henrykironde** [comment]
You can contribute to it.

**Comment by henrykironde** [comment]
@piyushchauhan I will close for now since we had to reorganize some the design when it comes to logging. Will open / reference this PR in the future

**Pull request closed without merging**
