### PR TITLE
Add path argument for altering install directories

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request aims to fix: #1137. It adds an optional `data_dir` argument to provide a more straight forward custom directory for installation of datasets.

### CODE REVIEW

**Comment by henrykironde** [comment]
Good start @harshitbansal05

**Comment by zhangcandrew** [comment]
Thanks @harshitbansal05! Henry and I reviewed it over here, I included a PR into your branch with some fixings, but things look pretty good. Test them out, see if it feels good. We're trying to enforce it now so that the -t or -f functions ONLY deal with the table name or the file name, but don't have any path information whatsoever. This would save us a lot of headache and make the code a bit easier too. 

The -d flag would be responsible for all information on the path. See how it feels. We can create some test for it afterwards too.

**Comment by harshitbansal05** [comment]
@henrykironde I have made the suggested changes, but I could not understand what you mean by adding an option value to the tests. Could you please explain it in a little more detail?

**Comment by henrykironde** [comment]
@harshitbansal05, I could see why we are failing, we are taking table name as only a file name, but in the engines we are using the file name as a pull path.

```python
       ("table_name",
         "Format of table name",
         os.path.join(DATA_DIR, "{db}_{table}.csv")),
```
I think it should be 
```python
       ("table_name",
         "Format of table name",
         "{db}_{table}.csv"),
```
and In the sqlite i[nterface](https://github.com/weecology/retriever/pull/1245/files#diff-6eeaff0b60ef0bad51fbc6a033928c46R94) we are still using  file_dir. 
The same applies to fetch function.
However, we may still have SQlite fails on regression after these changes and we shall have to change things again in the tests. The tests will be a separate commit after we have figured out what exactly is happening

**Comment by harshitbansal05** [comment]
@henrykironde I do not understand, what you mean by the problem caused by the `table_name`. As far as I understand, the error is only because of renaming the argument `file_dir` to `data_dir` for the sqlite and msaccess engines without the corresponding changes in the test files. Also, the travis error logs do not throw any error for csv tests.
Also, if I do not make the changes in the tests, the build would fail. So, is it fine to push with the builds failing?

**Comment by harshitbansal05** [comment]
Also, presently, I am not changing the format of the argument `table_name` for csv, etc. It still is of the form `os.path.join(DATA_DIR, "{db}_{table}.csv"))`. So, the task of changing the table_name argument to the form ` "{db}_{table}.csv"` should also be done in this pr?

**Comment by henrykironde** [comment]
> @henrykironde I have made the suggested changes, but I could not understand what you mean by adding an option value to the tests. Could you please explain it in a little more detail?

The first design did not need a change on tests since we are adding optional args to the function signature, which was only used when set, `install_example(dataset, file ="data.file_name", data_dir = default_DATA_DIR) `.  data_dir was defaulting to "." in the function, adding it would have the same behavior for test. However a new test would be required to show that if  data_dir was set to a different location `data_dir = "new_loc"`, we would still get the data needed.

In the new design, it seems like a lot is changing . We assume that table name, or file name should only be a name not a path. And data_dir should default to "." or DATA_DIR.

**Comment by henrykironde** [comment]
> So, the task of changing the table_name argument to the form ` "{db}_{table}.csv"` should also be done in this pr?
I think we should, we forgot to add that. https://github.com/harshitbansal05/retriever/pull/2

**Comment by harshitbansal05** [comment]
@zhangcandrew I have made the appropriate changes, however, am unable to understand one thing. The tests would fail with the corresponding changes. So should I push the commit with the tests failing or there is some other workaround to it?

**Comment by zhangcandrew** [comment]
Hey @harshitbansal05! If you merge harshitbansal05#2 in, I think the checks should pass.

**Comment by harshitbansal05** [comment]
@henrykironde @zhangcandrew could you please review it now?

**Comment by zhangcandrew** [comment]
Cool. Just wondering, why did you add `def table_name()` to the xml, csv, and json engines? I think it should be able to work ok w/o those functions

**Comment by harshitbansal05** [comment]
@zhangcandrew, the original implementation of the function `table_name` returned the entire name of the table along with the directory for xml, csv and json engines. So, I had overridden the method to make it consistent with the previous implementation.

**Comment by henrykironde** [comment]
Thanks folks, good work @harshitbansal05,  I think the goal of the changes was to use the 
`data_dir` as the path and then the file names should only be the base name. After going through this with @zhangcandrew, we came up with that design and sent you the PR. This new design eliminates the return of table_name as a full path. Which you have correctly implemented but added 
`def table_name() `making it wrong. 

If you think that the design has something wrong, please let us know. :) we shall be more than happy to rethink of the design. Right now I think the code would be fine with out 
`def table_name()`

**Comment by harshitbansal05** [comment]
@henrykironde, I agree. There were some dependencies on the function `table_name` which required the entire path of the table including the directory. Two of them were `table_exists` in the json and csv, and `open_fw` in json, csv and xml files(although the former has no usage). I have now made changes to those dependencies and removed the overridden methods. Hope this would work.

**Comment by harshitbansal05** [comment]
@henrykironde do any more changes have to be done or should I squash the commits?

**Comment by harshitbansal05** [comment]
@henrykironde @zhangcandrew could you please review it now?

**Comment by henrykironde** [comment]
A big 👍 for getting this everyone who contributed. 
Thanks @ashishpriyadarshiCIC for getting this to the ready stage.

**Pull request merged**
