### PR TITLE
Fixes 683: restructure project by moving core codes in sub-directory

### LINKED ISSUE #683: Move main package into subdirectory
The root directory has gotten pretty crowded, and standard structure for Python projects is to have the main package code in a subdirectory with the package name (see http://docs.python-guide.org/en/latest/writing/structure/).

### PR DESCRIPTION
**Pull request by kunalpal**

### CODE REVIEW

**Comment by henrykironde** [comment]
What system are  you using?
OS:
python version:

**Comment by kunalpal** [comment]
I am using OS X Sierra. Python version 2.7.11 and 3.5.2.

**Comment by ethanwhite** [comment]
LGTM and tests well locally. @henrykironde mentioned that there may be some things to consider with the `docs` build so I'll let him describe any potential things to clean up there.

**Comment by henrykironde** [comment]
Using the [developer Documentation](http://retriever.readthedocs.io/en/latest/developer.html),  run `sphinx-apidoc` to update the Documentation.
After generating the required files edit them to remove files that may not be needed.

**Comment by kunalpal** [comment]
I have rebuild the docs. There are a couple of changes but apart from that most of the docs seem to be similar.

**Comment by henrykironde** [comment]
@kunalpal , 

1. Clean your repository sinse you have a new file structure. (Also remove the dist and build folder. Remove the *.egg* file too)

2. Uninstall the old copy of retriever. ``pip uninstall retriever``. Repeat this to make sure that no retriever is installed.

3. Install the fresh copy and run `sphinx-apidoc` again. The best way is to create a temporary directory `source`  where you will dump the files. Move the created files into the doc folder.

4. Test the files by running `make html` to see if there are what you expect

**Comment by kunalpal** [comment]
I have done everything you referred in the preceding comment. The generated html is the same. However, I have removed version and setup submodule from the generated documents since they pose error during `make html`. The generated html though reflect all the changes in the modified docs.

**Comment by henrykironde** [comment]
@kunalpal, lets do a clean up on the commits. 
Squash them and only leave the ones that we really want.

**Comment by ethanwhite** [comment]
LGTM once the commits are squashed. A single commit should be good for this kind of change.

Thanks for the contribution @kunalpal!

**Comment by ethanwhite** [comment]
And it looks like we've merged something that introduces a conflict, so if you can squash this into one non-conflict commit we'll be all set. Thanks!

**Comment by kunalpal** [comment]
Hi @henrykironde, I have squashed all the changes into two commits one for restructuring and another for the documentation updates. I hope that it would be easy to follow now. Looking forward to the review and suggestions.

**Comment by henrykironde** [comment]
@kunalpal, Thank you for the good work. We have got this merged locally.

**Pull request closed without merging**
