### PR TITLE
Print exception message if script not loaded on installation

### PR DESCRIPTION
**Pull request by goelakash**
Prints description of error when `__init__.py` fails to compile script

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @goelakash. Since it fails on codecov, we could bring this in later.
I suggest combining these changes to the json package branch you working on.

**Comment by henrykironde** [comment]
could you also include the output before and output after the changes.

**Comment by goelakash** [comment]
@henrykironde This doesn't change the output currently as all the scripts compile successfully. I just thought about adding an exception description for debugging script compilation in the future.

**Comment by henrykironde** [comment]
Its okey, I will go ahead and close this. We shall include it later as we work on the compile module or something related

**Pull request merged**
