### PR TITLE
Fix:741 - Test, install new Script functionality.

### PR DESCRIPTION
**Pull request by ShivamNegi**
Preliminary code for the feature request #741

### CODE REVIEW

**Comment by henrykironde** [comment]
why are you closing this? Just wondering.

**Comment by ShivamNegi** [comment]
I added some other commits to the same branch. So they have appeared here too. I am looking for how to correct it.

**Comment by henrykironde** [comment]
Ah okey got it, Let me know if you want any help on that

**Comment by ShivamNegi** [comment]
Yup some help would be great. I have added some more commits but they keep updating this pull request.

**Pull request closed without merging**
