### PR TITLE
[WIP] adds support for Frictionless datapackage weecology#1404

### PR DESCRIPTION
**Pull request by pathak-mayurdeep**

### CODE REVIEW

**Comment by henrykironde** [comment]
@pathak-mayurdeep, this is a good start.
Let us first change the list in the `scripts/datapackages.yml`. The old ones are outdated.
Try to run some commands to see if everything runs as expected.
Paste some sample commands that you have run after.

**Comment by pathak-mayurdeep** [comment]
I am facing some problems while trying to build the package.
Initially, I created another branch and added some new data package urls and removed the old ones.
 `master` -> `datapackage` -> `dp_new_additions` 
Then, I tried to build the package with the `dp_new_additions`  branch

image
image

There are other errors, but my main problem is it didn't load the correct `datapackages.yml` content, instead it is somehow getting the original `datapackages.yml` even though I am in the `dp_new_additions` branch where I have added the new list.

I then tried making a zip of the whole `dp_new_additions` branch
and used `pip install 'path_to_archive' ` 

image

image

It still isn't getting the updated `datapackages.yml`

**Comment by henrykironde** [comment]
The way the search for data packages works is that we start in the working directory and them we move to the script directory if present and then `~/.script` directory.
If we have a script in the working directory and in the` ~/.script` directory, we  use the script in the working directory over  `~/.script `directory.

The same should apply to `datapackages.yml` and the data packages in there

**Comment by henrykironde** [comment]
Things that we should note
 Some fields in the  `Frictionless datapackage` are different from the retriever data package description. One field I have see is the path. The path in the data retriever refers to the path of the file in the `~/.retriever/[scriptname]` directory while the path in 
` Frictionless datapackage ` refers to the url link.

**Comment by pathak-mayurdeep** [comment]
> The way the search for data packages works is that we start in the working directory and then we move to the `script `directory if present and then `~/.script` directory.
> If we have a script in the working directory and in the` ~/.script` directory, we use the script in the working directory over `~/.script `directory.
> 
> The same should apply to `datapackages.yml` and the data packages in there

Thanks! that explains everything..

**Comment by pathak-mayurdeep** [comment]
> Things that we should note
> Some fields in the `Frictionless datapackage` are different from the retriever data package description. One field I have see is the path. The path in the data retriever refers to the path of the file in the `~/.retriever/[scriptname]` directory while the path in
> `Frictionless datapackage` refers to the url link.

Yes, I see this problem..
image

**Comment by henrykironde** [comment]
Do we have a PR for this?

**Comment by pathak-mayurdeep** [comment]
No, not yet..
I'll create the PR for this..

**Comment by ethanwhite** [comment]
Replaced by #1489

**Pull request closed without merging**
