### PR TITLE
Improve output when connection is not made

### PR DESCRIPTION
**Pull request by ashishpriyadarshiCIC**
Solves issue #1247

### CODE REVIEW

**Comment by henrykironde** [comment]
How did you test this ?

**Comment by ashishpriyadarshiCIC** [comment]
The issue of `Done` showing up after an exception was there for every type of exception. So, I recreated some different type of errors like I disabled the internet, made some changes on the source code to create some errors, etc.

**Comment by henrykironde** [comment]
Okey that is a good start. Now try to run the same commands in issue when you have stoped both the Postgres and Mysql server. Let me know what you get.

**Comment by ashishpriyadarshiCIC** [comment]
Here is the output :- 
screenshot from 2019-03-02 11-44-38
screenshot from 2019-03-02 11-45-55

**Comment by henrykironde** [comment]
Could we find away to catch that error?

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde Are you talking about catching the error on the methods to connect to the server because the message `Done!` would have been there even if the error was caught at the method where the connection is made. I'll try to catch the error at the get connect method and will see if there is a difference.

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde I've made a small change. Can you please review it?

**Comment by henrykironde** [comment]
When you run the command without databases up, what do you get?

**Comment by ashishpriyadarshiCIC** [comment]
Here it is :- 
screenshot from 2019-03-03 22-19-26

**Comment by ashishpriyadarshiCIC** [comment]
@henrykironde Is this ok?

**Comment by henrykironde** [comment]
I feel like we are handling it at a higher level. 
The Engine() member function `connection` gets to conn after `get_connection(): ` in the other inheriting engines, If I am correct.
From a quick look, I think we need to revisit def get_connection(self): in the Postgres and Mysql engines. Let me know if I am clear

**Comment by ashishpriyadarshiCIC** [comment]
I might have to close this PR and open a new PR as I messed up many things while using git.

**Pull request closed without merging**
