### PR TITLE
Issue 441: Remove the GUI and all references

### PR DESCRIPTION
**Pull request by Deborah-Digges**
1. Removed the _appdoc folder
2. Removed the graphical parameter to the function `check_for_updates`
3. Removed references of the GUI app from the docs
4. Removed the GUI option from the CLI options
5. Used help as the default option instead of launching the GUI
6. Removed the app folder
7. Made changes to setup.py to remove the check for wx
8. Made changes in setup.py to remove retriever.app as a module
9. Made sure all tests are running
10. Checked installation 
11. Checked a few CLI options(though not exhaustively)

Fixes: https://github.com/weecology/retriever/issues/441

### CODE REVIEW

**Comment by Deborah-Digges** [comment]
Open items:

1. `isgui` flag in `__init__.py`. It is used for windows installations. Can I remove it?
2. In `lib/repository.py`, there is a section of code that shows a pop up to a user if the version of retriever that is running is outdated; this popup uses `wx`. For now, I have commented this section. We will have to replace this with a CLI confirmation message

**Comment by Deborah-Digges** [comment]
The AppVeyor build job is failing with this message:

```
Build started
git clone -q https://github.com/weecology/retriever.git C:\projects\retriever
git fetch -q origin +refs/pull/499/merge:
git checkout -qf FETCH_HEAD
Specify a project or solution file. The directory does not contain a project or solution file.
```

Is there some configuration change needed for this?

**Comment by ethanwhite** [comment]
> The AppVeyor build job is failing...

We just turned on AppVeyor yesterday as part of testing #498, so none of the configuration is in yet and you can safely ignore that check.

**Comment by Deborah-Digges** [comment]
oh! thanks @ethanwhite.
@ethanwhite @henrykironde  Do let me know what you think about these changes.

**Comment by ethanwhite** [comment]
This is really excellent @Deborah-Digges! Thanks!!

The PR looks perfect to me, which just leave the two open items you noted:

1. The code on lines 57-64 can be replaced with `DATA_DIR = '.'`. That code handled the fact that installer based GUI on Windows would by default store data in the system path where the Windows installer put the retriever.
2. I actually think the entire `InitThread` class in `lib/repository.py` can be removed. As you can see from the comment on lines 116/117 or 87/88 (depending on new or original version of the file) this functionality as been disabled for a long time. If we're going to have the code start phoning home again to check for updates we'll need to implement it from scratch since the way we're handling releases has changed. So as long as removing `InitThread` doesn't break anything let's just go ahead and remove it.

**Comment by henrykironde** [comment]
@Deborah-Digges, I was going through the code and I think also lib/download.py needs to be revised.
over all we good to merge. We are waiting for some changes from the improve test PR.

**Comment by Deborah-Digges** [comment]
@ethanwhite @henrykironde thank you for reviewing these changes.

I have added the following changes according to @ethanwhite's suggestions:

1.  Removed the module lib/repository.py as the only function being used is check_for_updates, which internally calls InitThread to check for updates in the old way. I have also removed all references to this function
2. I have removed the `isgui` flag in `__init__.py` and also lines 57-64.

**Comment by ethanwhite** [comment]
Looks like that last set of changes broke something according to Travis. It might be passing locally due to cached versions of the dataset scripts. Try running

`retriever reset all`

And then rerunning the tests locally to see whether this still passes for you or not.

**Comment by Deborah-Digges** [comment]
Oh. It looks like the `InitThread` class can't be removed entirely, but only the auto update part. I've made the appropriate changes for this and followed the testing strategy you've mentioned. All tests are passing now 👍

**Comment by ethanwhite** [comment]
Ah, got it. Sorry about pointing you in the wrong direction on that.

This looks ready to go to me. Thanks so much for your help on this! In it goes.

**Comment by Deborah-Digges** [comment]
Thank you for your prompt reviews, Ethan. 👍

**Pull request merged**
