### PR TITLE
Create nd-gain.json

### PR DESCRIPTION
**Pull request by shreyneil**
The following PR fixes the following issue https://github.com/weecology/retriever/issues/988.

### CODE REVIEW

**Comment by henrykironde** [comment]
@shreyneil great addition to the retriever 👍 .

1. We should rename this dataset `nd-gain`.
2. Since this dataset is archived. The current retriever version can handle these files as the example I have created for you. #1048. (Instead of a python file, we can use the `Json` data package specification)
3. I do think we should add all the files (data). When creating the resources, only specify the fields for the tables in the trends folder. The rest of the tables in other folders should be left unspecified. The retriever will automatically identify them. 

4. names of the tables(`resource name`) could be a combination of the folder and file. e.g `trends_gain`


Let me know if anything is not clear.

**Comment by shreyneil** [comment]
Will do sir, but everytime i run my json file i am always getting a line contains null byte error, how do i remove it ?

This is my json file:

{
  "citation": "NA", 
  "description": "The ND-GAIN Country Index summarizes a country's vulnerability to climate change and other global challenges in combination with its readiness to improve resilience. It aims to help governments, businesses and communities better prioritize investments for a more efficient response to the immediate global challenges ahead.",
   "homepage": "http://index.gain.org/",
   "encoding": "UTF-8",
  "keywords": [
    "ND-Gain"
  ],
  "name": "nd-gain",
  
  "archived": "zip",
  "resources": [
    {
      "path": "resources/trends/",
      "dialect": {
        "delimiter": ","
      },
      "name": "trends_gain",
      "schema": {
        "fields": [
          {
            "name": "IS03",
            "type": "char"
          },
          {
            "name": "Name",
            "type": "char"
          },
          {
            "name": "Standard",
            "type": "double"
          },
          {
            "name": "Sign",
            "type": "double"
          }
          
        ]
      },
      "url": "https://gain-new.crc.nd.edu/assets/gain/files/resources-2017-03-10-14h04.zip"
              
    }
  ],
  "retriever": "True",
  "retriever_minimum_version": "2.0.dev",
  "title": "ND-Gain",
  "urls": {
        "trends_gain": "https://gain-new.crc.nd.edu/assets/gain/files/resources-2017-03-10-14h04.zip"
    },
  "version": "1.0.0"
}

**Comment by shreyneil** [comment]
Done.

**Comment by shreyneil** [comment]
@henrykironde  Please verify, changes have been made.

**Comment by shreyneil** [comment]
@henrykironde  can you please review the changes. it would be great if you could do so.

**Comment by henrykironde** [comment]
@ethanwhite, any input on this dataset's namespace. I mean after installing into a database

**Comment by ethanwhite** [comment]
@henrykironde this isn't currently installing locally for me using `master`:

```
$ retriever install sqlite nd-gain
=> Installing nd-gain


Downloading /home/ethan/.retriever/raw_data/nd-gain/resources-2017-03-10-14h04.zip...
100%  1 seconds [Errno 2] No such file or directory: '/home/ethan/.retriever/raw_data/nd-gain/resources/trends/gain.csv'
Done!
```

**Comment by shreyneil** [comment]
@henrykironde can you look into this?

**Comment by henrykironde** [comment]
@shreyneil, thanks for the reminder. We are testing this PR

**Comment by henrykironde** [comment]
@shreyneil this should have  "retriever_minimum_version": "2.1.dev", since this new feature does not work in any other version.

**Comment by shreyneil** [comment]
Done sir!

**Comment by henrykironde** [comment]
Thanks for working on this @shreyneil 👍

**Pull request merged**
