### PR TITLE
Add tests for more code coverage 

### LINKED ISSUE #1637: Improve test coverage
Currently Codecov code coverage is at 60%. Let us aim for 75%+

### PR DESCRIPTION
**Pull request by Nageshbansal**
Fixes #1637

### CODE REVIEW

**Review by Nageshbansal — COMMENTED** [review]
tests for create_socrata_datasets  and create_rdataset

**Comment by Nageshbansal** [comment]
@henrykironde, I think the acton-lake dataset link is broken as we can see in [line 244](https://github.com/weecology/retriever/runs/5229988901?check_suite_focus=true#step:12:244) , that's why tests are falling. 
In the acton-lake script these following URLs are broken,
https://github.com/weecology/retriever/blob/c4840b303a5af29c9bed3b99b340722b4e7f3611/scripts/acton_lake.json#L34
https://github.com/weecology/retriever/blob/c4840b303a5af29c9bed3b99b340722b4e7f3611/scripts/acton_lake.json#L58
https://github.com/weecology/retriever/blob/c4840b303a5af29c9bed3b99b340722b4e7f3611/scripts/acton_lake.json#L70
https://github.com/weecology/retriever/blob/c4840b303a5af29c9bed3b99b340722b4e7f3611/scripts/acton_lake.json#L85
https://github.com/weecology/retriever/blob/c4840b303a5af29c9bed3b99b340722b4e7f3611/scripts/acton_lake.json#L98

**Comment by Nageshbansal** [comment]
@henrykironde can you please review this PR.

**Comment by henrykironde** [comment]
This is good, there are some changes that we should make. Let's go through this together when you get free time.

**Comment by Nageshbansal** [comment]
Yeah sure.
Thanks

**Comment by henrykironde** [comment]
This is not yet updated as we discussed.

**Pull request merged**
