### PR TITLE
Add raw data for sample-dataset

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Please merge this before #1338 because this data is needed for testing in #1338

### CODE REVIEW

**Comment by henrykironde** [comment]
Is it possible to call this something else instead of `Portal_rodents_19772002.csv`, and also change the name of the script?

**Comment by apoorvaeternity** [comment]
Yeah. What should I name it to? I have named the script as `sample-dataset`.

**Comment by henrykironde** [comment]
May be `sample_dataset.csv`

**Comment by apoorvaeternity** [comment]
Okay. So keeping the name of the script as `sample-dataset`?

**Comment by henrykironde** [comment]
I think that works or even something like `sample-dataset-provenance` or` dataset-provenance` or `test-dataset-provenance`.

**Pull request merged**
