### PR TITLE
Documentation for retriever

### PR DESCRIPTION
**Pull request by henrykironde**
Please have a look and let me know the changes as we continue the work on this branch

A copy of the current documentation is available in the link below

http://deletedret.readthedocs.org/en/docbuild/index.html

### CODE REVIEW

**Comment by davharris** [comment]
Some comments on how it looks:

- [ ] I think the colors may be reducing readability and navigability. In my browser at least, the solarized-like yellow on light gray (or white) in the sidebar is particularly hard to read. It's also not as easy as I think it should be to distinguish text and non-visited links.

- [ ] For the introduction, a smaller logo and a horizontal arrangement for the badges would free up a lot of space.  On my 13" monitor, I can only see the first three lines of the introduction before scrolling down.

- [ ] The link/text in the far upper left (in the green header bar above the logo) that says "EcoData Retriever-v1.7.0 »" is almost visually indistinguishable from the background

- [ ] The Travis badge in the introduction looks pixellated on my screen.  I think Travis provides SVG badges that will look more consistent.

- [ ] The drop shadows in the headers make them harder to read

- [ ] I get some slightly annoying scrolling behavior on my Mac in Chrome: if I scroll down on the main page, the sidebar sort of tries to scroll along with it and then snaps back and then tries to start scolling again.

**Comment by emchristensen** [comment]
Couple comments:
1) I agree with Dave about colors, the table of contents is kind of hard to read
2) In the introduction section there are subsections called "Installing from source" and "To Install from source" -- combine these two sections?
3) Can you put links to places you can download the required and optional python packages?
4) Table of contents looks a little verbose - shorter section titles would make it easier to read (e.g. "Writing and loading scripts for the ecodata retriever" -> "Contributing data")
5) In the introduction, maybe put in a sentence explicitly saying something like "EcoData Retriever is a downloadable software package..." to prepare the uninitiated for the idea that they're going to have to download and install a thing -- or maybe by the time they get to this page they already have an idea of what using the tool will entail

**Comment by MarconiS** [comment]
Hey Henry!
my comments:
1) I agree on the colors, I'd use a different scheme 
2) there is a typo in the "Writing and loading Scripts for the EcoData Retriever¶":
   - The Eco Data Retriever uses a simple a simple format (twice "a simple")
3) I would include the link of the github project page to make easier to clone the repo (or directly the string to use from the command line; if I am not wrong it is not explicitly provided, if not passing through the ecodataretriever.org web page);  
4) I agree with Erica on the table of content; 
5) Agree with Dave on arranging the badges horizontally to gain space on the introduction page

**Comment by sdtaylor** [comment]
There is no documentation on the GUI, which definitely needs some. It took me a while to figure out where csv files were being downloaded and how to change that.

**Comment by ethanwhite** [comment]
Great recommendations everyone. I really appreciate the engagement. Thanks! :raised_hands: 

1. I agree on the colors, and since this is a docs site let's keep them nice and simple. I actually like what looks to be the default: e.g., http://jupyter-notebook.readthedocs.org/en/master/. This template also includes a link to "Edit on GitHub", which addresses @MarconiS's suggestion of a link to GitHub.
2. I think we can drop the badges and logo entirely here
3. I agree with all of the other suggestions and especially @sdtaylor's point about instructions for the GUI.

**Pull request closed without merging**
