### PR TITLE
Forcing value to type str for keys starting with '*'

### PR DESCRIPTION
**Pull request by goelakash**
Using str(e) unconditionally.
@henrykironde @ethanwhite

### CODE REVIEW

**Comment by henrykironde** [comment]
for the record, could you give some scenarios/reasons for the change.

**Comment by goelakash** [comment]
While porting code to Python3, we need to import `builtins.str`, which is of different type than python2 `str`. This if else condition was using `eval(value)`, which was causing problems in doing this.

Either way, forcing `str` to `str` doesn't cause a problem I think.

**Comment by henrykironde** [comment]
Okey, I think since this will be introduced when we shifting to python 3, I will keep it open and merge it when we are merging all changes related to the python 3 shift :+1: .  Hope the wait does not affect our progress forward.

**Comment by henrykironde** [comment]
`` if e.__class__ != str else "'" + e + "'"  `` interesting code. :+1:

**Comment by goelakash** [comment]
Delimiters are always strings, I just checked. 
Why this code was introduced, I don't know, since we could easily flag those scripts as invalid which didn't have string delimiters.

**Comment by henrykironde** [comment]
merging because the added line removes redundancy in code

**Pull request merged**
