### PR TITLE
Add partners in flight species assessment dataset

### PR DESCRIPTION
**Pull request by shreyneil**
The Following PR is for fixing issue https://github.com/weecology/retriever/issues/386. Please review and get back.

### CODE REVIEW

**Comment by henrykironde** [comment]
Update the `version.txt` file correctly. The version number should be `1.0.0`

**Comment by henrykironde** [comment]
Thanks @shreyneil, please provide me with some of the results from 
Please provide me with some of the results of  `retriever install sqlite partners_in_flight_species_assessment` and also make sure that you check the data installed. Once you have finished to confirm that the data is clearly installed on your local system, Let me know.

You can use sqlite browser to confirm that the data is installed well. Also share some images of the data after it is installed http://sqlitebrowser.org/.
In this way it will make review easy and faster.

By the way, :+1: on getting the commits squashed.

**Comment by henrykironde** [comment]
I recommend a name change to either `pif` or  `partners-in-Flight`. And I think partners in flight sounds better `partners-in-Flight`

**Comment by ethanwhite** [comment]
+1 to `partners-in-flight` (with a lower case `F` on `flight`)

**Comment by henrykironde** [comment]
@shreyneil, it's not the urls problem in this case. the script gives you those results because the script is clearly wrong. Look at the fields in the downloaded files and your fields. Please take time and see that the fields you have given match those in download files. Also remember to always run python version.py after any work on scripts and update the version.txt file. 

I have looked at the fields in the dowloaded files from those links and the fields and they don't match

**Comment by henrykironde** [comment]
for example 
```
        {
            "name": "0",
            "type": "char"
          },
          {
            "name": "M",
            "type": "char"
          },
          {
            "name": "",
            "type": "char"
          },
          {
            "name": "",
            "type": "char"
          },
          {
            "name": "",
            "type": "char"
          },
          {
            "name": "4",
            "type": "char"
          },
          {
            "name": "5700",
            "type": "char"
          },
```
what where did you get these fields?

**Comment by ethanwhite** [comment]
Also, the name of the datasets also needs to be updated in `version.txt`.

**Comment by shreyneil** [comment]
@henrykironde there was some problem with my csv reader that messed up the headers, Please review.

**Comment by henrykironde** [comment]
Looks like we are getting there. Now run the sample install command, paste the results as I requested before

**Comment by shreyneil** [comment]
shreyash@shreyash-Inspiron-13-5378:~$ retriever install sqlite partners-in-flight
=> Installing partners-in-flight
Creating table partners_in_flight_Global_2017_United_States...
Progress: 199/199 rows inserted into partners_in_flight_Global_2017_United_States totaling 199:

Creating table partners_in_flight_Global_2017_MEXICO...
Progress: 199/199 rows inserted into partners_in_flight_Global_2017_MEXICO totaling 199:

Creating table partners_in_flight_PIF_2012_BCR_all...
Progress: 199/199 rows inserted into partners_in_flight_PIF_2012_BCR_all totaling 199:

Creating table partners_in_flight_Global_2017_Canada...
Progress: 199/199 rows inserted into partners_in_flight_Global_2017_Canada totaling 199:

Creating table partners_in_flight_Global_2017_CAM...
Progress: 199/199 rows inserted into partners_in_flight_Global_2017_CAM totaling 199:

Done!

**Comment by henrykironde** [comment]
@shreyneil, Looks great. I will do some more checks and merge it

**Comment by henrykironde** [comment]
Remove the encoding line  "encoding": "UTF-8", and also rebase.

**Pull request merged**
