### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by goelakash**
Added absolute imports (which are default on python 3).
Needed to add symlinks to cloned repos from `lib\site-packages\` to for the package `retriever` to be found.

### CODE REVIEW

**Comment by goelakash** [comment]
@henrykironde Figured that only VERSION was needed from `retriever.__init__.py` before installation of `retriever` package, so moved that to `setup.py`. Otherwise the build fails on travis and appveyor.

**Comment by henrykironde** [comment]
@goelakash, Please, could you clean up the commits for this PR and edit the description to be more clear.

**Comment by goelakash** [comment]
@henrykironde Yes, but I wanted to have your opinion on whether this is the right way to store the `VERSION` variable. Keeping two copies and updating them both seems not to be a good idea to me.

I am also considering moving the entire retriever package code to a sub-dir called `retriever` and test those changes. This is because the `setuptools.setup` function for python3 seems to have a problem in correctly detecting the package in the same folder as `setup.py`.

**Comment by henrykironde** [comment]
@goelakash, I guess you mean something like this `http://www.diveintopython3.net/packaging.html#structure`
Please, go ahead if this structure works as default for the python3 shift and correctly detecting the package locations.
About the version, having one copy is definitely a good idea as long as we can access effectively from there, I think for now we can go with what you have suggested.

**Comment by goelakash** [comment]
@henrykironde #525 is the solution suggested by @ethanwhite . Guess I should rebase on that once that is merged?

**Comment by henrykironde** [comment]
@goelakash, I think we can close the other one.
We then include the suggested changes in a new branch or even here. 
then squash the changes to represent something like changing setup module to create version module or anything that is appropriate.

**Comment by ethanwhite** [comment]
It doesn't matter to me which PR it goes through, but I'd like to get the change in #525 in quickly since we basically have a broken build at the moment (i.e., #522).

**Comment by goelakash** [comment]
@henrykironde Please review this.

**Pull request merged**
