### PR TITLE
Assimilating insert_limit with all the engines.

### PR DESCRIPTION
**Pull request by shreyneil**
Changes are in reference with the following issue https://github.com/weecology/retriever/issues/939#issuecomment-354907206
Please verify and get back.

### CODE REVIEW

**Comment by shreyneil** [comment]
Please verify and get back.

**Comment by shreyneil** [comment]
@henrykironde  Sir,hope you could merge this pr.

**Comment by henrykironde** [comment]
Thanks @shreyneil.  This is ready, but we shall merge it after one complicated PR that we want to get in

**Comment by shreyneil** [comment]
@henrykironde ok sounds good, just let me know i can help with the complicated PR.

**Comment by henrykironde** [comment]
@shreyneil Thank you for working on this issue. 👍 
Sorry if it took long, sometimes we have to run several tests and see what happens even with small changes

**Pull request merged**
