### PR TITLE
Remove use_cache parameter from download

### PR DESCRIPTION
**Pull request by ShivamNegi**

### CODE REVIEW

**Comment by ShivamNegi** [comment]
There is no `--not-cached` parameter for the CLI. This went into the interface function by mistake.

**Comment by henrykironde** [comment]
I guess we should remove the same in 

```
retriever\retriever\__main__.py:
  156  
  157          if hasattr(args, 'debug') and args.not_cached:
  158:             engine.use_cache = False
  159          else:
  160:             engine.use_cache = True
  161  
  162          if args.dataset is not None:

retriever\retriever\lib\download.py:
   20      }
   21      engine = choose_engine(args)
   22:     engine.use_cache = use_cache
   23  
   24      scripts = name_matches(script_list, args['dataset'])

retriever\retriever\lib\engine.py:
   41      pkformat = "%s PRIMARY KEY %s "
   42      script = None
   43:     use_cache = True
   44      debug = False
   45      warnings = []
   ..
  411              finally:
  412                  # Download is complete, set to prevent repeated downloads
  413:                 self.use_cache = True
  414  
  415      def download_files_from_archive(self, url, filenames, filetype="zip",

retriever\retriever\lib\install.py:
   13      """Install scripts for retriever."""
   14      engine = choose_engine(args)
   15:     engine.use_cache = use_cache
   16  
   17      script_list = SCRIPT_LIST(force_compile=True)
```

**Comment by ShivamNegi** [comment]
In `_main_`, `download` and `engine` the `use_cache` parameter is required. The CLI offers support for `--not-cached` in case of installing scripts, but not for downloading them. So the mentioned occurrences are required.

**Comment by henrykironde** [comment]
I actually cant see it being used, when I searched.

**Comment by henrykironde** [comment]
I see it

**Comment by henrykironde** [comment]
Looks good, I will go ahead and merge

**Pull request merged**
