### PR TITLE
Add script for Palmer et al 2007

### PR DESCRIPTION
**Pull request by dmcglinn**
This commit adds the Oosting forest plant dataset from Palmer et al. 2007 which is an ecological archives dataset: http://esapubs.org/archive/ecol/E088/162/

### CODE REVIEW

**Comment by dmcglinn** [comment]
From what I can tell it looks like the Travis CI build failed because of tests on three datasets that are unrelated to my changes.

**Comment by ethanwhite** [comment]
Yeah, the Travis failure is discussed in #269. We've run into this before where some subtle difference in the version of the database management system between our systems and the CI causes a mismatch in the hashes. I'm trying to figure out a more stable way to structure those tests. Just. Need. More. Time. :)

Have you tested this locally? When I run the PR into SQLite I get an error:

```
ethan@oryx:~/$ retriever install sqlite Palmer2007 -f palmer2007.sqlite
=> Installing North Carolina forest plants (Ecological Archives 2007)
Creating table Palmer2007_environment...
Inserting rows to Palmer2007_environment: 289 / 289
Creating table Palmer2007_pres...
Inserting rows to Palmer2007_pres: 21253 / 21253
Creating table Palmer2007_species...
Inserting rows to Palmer2007_species: 224 / 224
Creating table Palmer2007_trees...
Couldn't create table (near "TEXT": syntax error). Trying to continue anyway.
INSERT INTO Palmer2007_trees (id, code, fx, fy, d90, c90, d98, c98, f1, f2, f3, f4, azm, tx, ty, nx, ny, cl, check, notes) VALUES (574, 'POST', '0', 0, '.', '.', '.', '.', '', '', '', '.', '.', '0', '2400', '0', '0', '.', null, null);
near "check": syntax error
```

Are you seeing the same thing?

**Comment by dmcglinn** [comment]
I see the same error for sql as well. I'll try to see which rows in which table are causing the problem.

**Comment by dmcglinn** [comment]
The error is cause because there are both empty cells and cells with "." that are intended to be null values. Here is a reference to R code that I developed to deal with the problems. 

https://github.com/weecology/mete-spatial/blob/master/scripts/spat_empir_data_filtering.R#L152

I suppose it is necessary to convert this R code to python?

**Comment by ethanwhite** [comment]
Nope, you just need to tell the retriever what the null values are. See the Null Values section of:
http://www.ecodataretriever.org/scripting.html

**Comment by dmcglinn** [comment]
sweet I'll take a look!

**Comment by dmcglinn** [comment]
I added dots ('.') and blanks ('') as null values see ea49302, but I'm still getting errors when installing to sqlite. Specifically the output messages from retriver are as follows:
```
$ retriever install sqlite Palmer2007
=> Installing North Carolina forest plants (Ecological Archives 2007)
Downloading Oosting_pres2.txt...
Creating table Palmer2007_pres...
Inserting rows to Palmer2007_pres: 21253 / 21253
Downloading species_codes.txt...
Creating table Palmer2007_species...
Inserting rows to Palmer2007_species: 224 / 224
Creating table Palmer2007_trees...
Couldn't create table (near "TEXT": syntax error). Trying to continue anyway.
INSERT INTO Palmer2007_trees (id, code, fx, fy, d90, c90, d98, c98, f1, f2, f3,
f4, azm, tx, ty, nx, ny, cl, check, notes) VALUES (574, 'POST', 0, 0, null, null, null, null, null, null, null, null, null, 0, 2400, 0, 0, null, null, null);
near "check": syntax error
Done!
```
I'm not sure what's causing the problems but maybe something in the column names that sqlite doesn't like? Also the dataset does have a stray comma in a column by itself row 12467 in column labeled d98. I tried to list comma as a null value as well but this caused problems I think because the notes column has commas throughout it.

**Comment by ethanwhite** [comment]
Turns out that `check`, which is one of the column titles, is a reserved keyword in SQL. You can replace the name by adding

`replace: check, someothernameforcheck`

immediately above `table: trees, http://esapubs.org/archive/ecol/E088/162/Oosting_Trees_1998.txt`

**Comment by dmcglinn** [comment]
Sweet thanks @ethanwhite! If there's no easy way to fix the stray comma on row 12467 I think this is ready to be merged.

**Comment by ethanwhite** [comment]
Is that comma on 12467 supposed to indicate a null? If so, then you could just add `,` to the list of nulls and it would get rid of it.

**Comment by dmcglinn** [comment]
I tried that but it threw errors I think because there are commas embedded
in the text in the last column which contains notes.

**Comment by dmcglinn** [comment]
here's the error message:
```
Daniel@MCGLINN-DELL ~/Documents/retriever/scripts (EA_palmer2007)
$ retriever install csv Palmer2007
Traceback (most recent call last):
  File "c:\Anaconda\Scripts\retriever-script.py", line 9, in <module>
    load_entry_point('retriever==1.6', 'console_scripts', 'retriever')()
  File "c:\Anaconda\lib\site-packages\retriever-1.6-py2.7.egg\retriever\__main__.py", line 40, in main
    script_list = SCRIPT_LIST()
  File "c:\Anaconda\lib\site-packages\retriever-1.6-py2.7.egg\retriever\__init__.py", line 88, in SCRIPT_LIST
    return [module.SCRIPT for module in MODULE_LIST(force_compile)]
  File "c:\Anaconda\lib\site-packages\retriever-1.6-py2.7.egg\retriever\__init__.py", line 67, in MODULE_LIST
    compile_script(join(search_path, script_name))
  File "c:\Anaconda\lib\site-packages\retriever-1.6-py2.7.egg\retriever\lib\compile.py", line 43, in compile_script
    nulls = [eval(v) for v in [v.strip() for v in value.split(',')]]
  File "<string>", line 1
    '
    ^
SyntaxError: EOL while scanning string literal
```

**Comment by ethanwhite** [comment]
Yep, you're totally right. I'd been assuming they were enclosed, but they aren't.

Thanks for this contribution @dmcglinn! It's going in.

**Pull request merged**
