### PR TITLE
Move script editing functions to the recipes repository

### PR DESCRIPTION
**Pull request by harshitbansal05**
@henrykironde @zhangcandrew another subpart of the original pr. It shifts the script's adding and editing functionalities to the recipes repository.

### CODE REVIEW

**Comment by henrykironde** [comment]
So are we closing the original PR? #1341

**Comment by harshitbansal05** [comment]
Yes, @henrykironde we would close the original pr, as Andrew said it would be better to split the pr into smaller pr's.

**Comment by zhangcandrew** [comment]
This looks good to me, can you make appropriate changes (either in this PR or another PR) to the retriever docs to remove any reference to editing jsons etc?

**Comment by harshitbansal05** [comment]
@zhangcandrew, the doc changes would be large. O think we can do it in a separate pr.

**Comment by harshitbansal05** [comment]
Also, should I simply remove the docs related to addition of scripts?

**Comment by zhangcandrew** [comment]
If you want you can try to migrate them over to retriever-recipes since the recipes repo will end up needing a new set of doc

**Comment by henrykironde** [comment]
@zhangcandrew, @harshitbansal05, where do you think we should put `autocreate_parser` functionalities? 
At this point we are have stand alone functions, I think we should make `retriever-recipes` a package with both CLI and interface, what do you think.

**Comment by harshitbansal05** [comment]
@henrykironde @zhangcandrew I removed the docs related to adding/editing scripts. However, more discussion is needed regarding the section 'Datasets Available'.

**Comment by zhangcandrew** [comment]
@henrykironde, I agree with that sentiment. I think retriever-recipes should have its own CLI to run, which I think can be implemented in a later PR after we've leveraged the changes we're trying to put in currently

**Comment by harshitbansal05** [comment]
@zhangcandrew @henrykironde I agree too, and I have begun the work to add a CLI interface to recipes repo.

**Comment by zhangcandrew** [comment]
This looks fine. Merging in, going to test out the retriever-recipes CLI

**Pull request merged**
