### PR TITLE
Moved VERSION to setup.py

### PR DESCRIPTION
**Pull request by goelakash**
and write its value to a separate __version__.py file.
#522 
@ethanwhite @henrykironde

### CODE REVIEW

**Comment by ethanwhite** [comment]
This is the right basic idea, but the convention is the have the member variable be `__version__`, so we should set this up so that the import in `__init__` is `from _version import __version__`.

@henrykironde - does this look like a reasonable general solution to you?

**Comment by henrykironde** [comment]
yes this is a good solution to keep the setup module and project source

**Comment by henrykironde** [comment]
This looks fine to me .

**Comment by ethanwhite** [comment]
We should still update this to match the standard.

**Pull request merged**
