### PR TITLE
adds bump-version script #1434

### PR DESCRIPTION
**Pull request by pathak-mayurdeep**
Wrote a python script to automatically update version numbers.

image

image

image

image

image

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @pathak-mayurdeep for the feature, it looks like it is what we want . There is however a tool that handles this, I wonder if you could compare the two and see.
https://medium.com/@williamhayes/versioning-using-bumpversion-4d13c914e9b8
https://pypi.org/project/bumpversion/

**Comment by pathak-mayurdeep** [comment]
I have done some research on this tool, and this is what I found.
It supports addition of git tags by adding `--tag` 
Allows easy increments of parts of the version numbers, where parts can be configured as required.

So we can either go with this tool and try to configure it for retriever, or we could create these features on our own. @henrykironde how should I proceed?

**Comment by apoorvaeternity** [comment]
+1 to using something like https://pypi.org/project/bump2version/ and configuring it for retriever. It's battle tested and is being used by several others. It is also a part of development and won't be used by our end users so I don't see any benefit of reinventing the wheels here.
@pathak-mayurdeep @henrykironde thoughts?

**Comment by pathak-mayurdeep** [comment]
@apoorvaeternity  Yeah, I agree. I'll try configuring it for retriever then. Thanks.

**Comment by henrykironde** [comment]
Closing ref #1460

**Pull request closed without merging**
