### PR TITLE
Refactor insert_statment for readability

### LINKED ISSUE #647: Refactor insert_statement in lib/engine
current status:

```
    def insert_statement(self, values):
        """Returns a SQL statement to insert a set of values."""
        columns = self.table.get_insert_columns()
        types = self.table.get_column_datatypes()
        columncount = len(self.table.get_insert_columns(join=False, create=False))
        insert_stmt = "INSERT INTO {} ({}) VALUES ".format(self.table_name(), columns)
        for rows in values:
            vals = rows
            insert_stmt2 = " ("
            for i in range(0, columncount):
                insert_stmt2 += "%s, "
            insert_stmt2 = insert_stmt2.rstrip(", ") + "),"
            n = 0
            while len(vals) < insert_stmt.count("%s"):
                vals.append(self.format_insert_value(None, types[n]))
                n += 1
            insert_stmt2 %= tuple([str(value) for value in vals])
            insert_stmt += insert_stmt2
        insert_stmt = insert_stmt.rstrip(", ") + ";"
        if self.debug:
            print(insert_stmt)
        return insert_stmt
```

This function could be refactor to improve readability

### PR DESCRIPTION
**Pull request by goelakash**
Fixes #647

### CODE REVIEW

**Comment by goelakash** [comment]
@henrykironde Looks good?

**Comment by henrykironde** [comment]
After reviewing the old version and the new version, both do not prevent sql injections since we are not letting sql do the processing of place holders.

**Comment by henrykironde** [comment]
A good implementation would be as shown, http://bobby-tables.com/python.html
MySQL or PostgreSQL, use` %s`  and SQLite uses `?`

**Comment by henrykironde** [comment]
We should also look at this #168

**Comment by goelakash** [comment]
@henrykironde This is a bulk insert statement, so in order to pass parameters to this query as argument to a `cursor` object to insert data in the table, the data will have to be available there as well, which will need refactoring of `add_to_table` and `execute` functions as well.

**Comment by henrykironde** [comment]
@goelakash, thanks for this PR

**Pull request merged**
