### PR TITLE
Mammal community db

### LINKED ISSUE #865: Error message: cannot import name 'urlretrieve' on Windows 10 home
The following retriever command generates an error: 
```
retriever install csv mammal-community-db
=> Installing Mammal Community DataBase (Thibault et al. 2011)

Downloading MCDB_sites.csv...
cannot import name 'urlretrieve'
Done!
```
The file is not downloaded

### PR DESCRIPTION
**Pull request by henrykironde**
Move  mammal-community-db to fixshare
https://figshare.com/articles/Data_Paper_Data_Paper/3552243
fixes #865

### CODE REVIEW

**Comment by henrykironde** [comment]
sample run

```
(venv35) ~\Documents\GitHub\retriever [mammal-community-db +1 ~0 -0 !]> retriever install sqlite mammal-community-db
=> Installing mammal-community-db

Downloading 5620542...
100%  1 seconds Creating table mammal_community_db_communities...
Progress: 7977 / 7977 rows inserted into mammal_community_db_communities totaling 7977:


Downloading 5620551...
100%  0 seconds Creating table mammal_community_db_species...
Progress: 700 / 700 rows inserted into mammal_community_db_species totaling 700:


Downloading 5620548...
100%  3 seconds Creating table mammal_community_db_sites...
Progress: 1000 / 1000 rows inserted into mammal_community_db_sites totaling 1000:


Downloading 5620545...
100%  1 seconds Creating table mammal_community_db_references...
Progress: 186 / 186 rows inserted into mammal_community_db_references totaling 186:


Downloading 5620554...
100%  3 seconds Creating table mammal_community_db_trapping...
Progress: 1169 / 1169 rows inserted into mammal_community_db_trapping totaling 1169:

Done!
```

**Comment by ethanwhite** [comment]
This is currently erroring for me. I think we need to update the urls at the bottom as well.

**Comment by henrykironde** [comment]
@ethanwhite it's updated. I think I might have forgotten to push, thanks for the catch.

**Comment by ethanwhite** [comment]
That did it. Thanks.

**Pull request merged**
